In [1]:
import pandas as pd 
import glob
from datetime import datetime 
import os
from bs4 import BeautifulSoup

In [2]:
INPUT_DATA_FOLDER = "<input your path for folder with parsed html>"

In [3]:
files_by_days = glob.glob(f"{INPUT_DATA_FOLDER}/*.html")

In [4]:
len(files_by_days)

print(files_by_days[0])

/Users/mac/Downloads/Python26/data/isw_raw/2023_11_05.html

In [6]:
all_data = []

for file in files_by_days:
    d = {}
    file_name = os.path.basename(file).replace(".html","").split("___")

    date = datetime.strptime(file_name[0], "%Y_%m_%d")
    url = file_name[0]
    
    with open(file,"r") as cfile:
        html_content = cfile.read()
        parsed_html = BeautifulSoup(html_content, 'html.parser')
        
        title = parsed_html.head.find("title").text
        link = parsed_html.head.find("link",attrs={"rel":"canonical"},href=True)
        if link is not None:
            link = link.attrs["href"]
        else:
            link = ""
        text_title = parsed_html.body.find('h1', {'class': 'title', 'id': 'page-title'})
        if text_title is not None:
            text_title = text_title.text
        else:
            text_title = title
        
        d = {
            'id': len(all_data) + 1,
            'date': date.strftime('%Y-%m-%d'),
            'short_url': url,
            'title': title,
            'text_title': text_title,
            'full_url': link,
            'html_content': html_content
        }
         
        all_data.append(d)

In [7]:
data = pd.DataFrame(all_data)

In [8]:
data['html_content'][1]

'<!DOCTYPE html>\n<html lang="en-US">\n<head>\n\t<meta charset="UTF-8">\n\t<meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n\t<!-- This site is optimized with the Yoast SEO Premium plugin v27.0 (Yoast SEO v27.0) - https://yoast.com/product/yoast-seo-premium-wordpress/ -->\n\t<title>Russian Offensive Campaign Assessment, August 14, 2022 | ISW</title>\n\t<link rel="canonical" href="https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/" />\n\t<meta property="og:locale" content="en_US" />\n\t<meta property="og:type" content="article" />\n\t<meta property="og:title" content="Russian Offensive Campaign Assessment, August 14, 2022" />\n\t<meta property="og:description" content="Russian and proxy troops in Ukraine are likely operating in roughly six groups of forces oriented on Kharkiv City and northeastern Kharkiv Oblast; along the Izyum-Slovyansk line; the Siversk-Lysychansk area; Bakhmut; the Avdiivka-Donetsk City area; and Southern Ukraine. The Kharkiv City and Siversk-Lysychansk groups are likely built around cores drawn from the Western and Central Military Districts respectively. The Izyum-Slovyansk axis is increasingly manned by recently formed volunteer battalions that likely have very low combat power. Wagner Group private military company (PMC) soldiers are in the lead around Bakhmut, while forces drawn from the Donetsk People’s Republic (DNR) predominate in the Avdiivka-Donetsk City area. Troops from the Southern Military District (SMD) likely formed the original core of forces in Kherson and Zaporizhzhia Oblasts but have been reinforced with troops of the Eastern Military District, Airborne Forces, and Rosgvardia. None of these groupings is homogeneous—elements of various military districts, proxy forces, volunteer units, and other formations are scattered throughout the theater. These dispositions suggest that Moscow is prioritizing the advance around Bakhmut and, possibly, toward Siversk with its Russian forces while seeking to draw on the enthusiasm of DNR forces to seize ground they have failed to take since 2014 on the Avdiivka axis. The high concentration of volunteer battalions around Izyum and Slovyansk suggests that that area is not a focus of Russian attention and may be vulnerable to Ukrainian counterattacks. The congeries of forces in and around Kherson Oblast may pose significant challenges to Russian command and control, especially if Ukrainian forces press a counteroffensive there." />\n\t<meta property="og:url" content="https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/" />\n\t<meta property="og:site_name" content="Institute for the Study of War" />\n\t<meta property="article:publisher" content="https://www.facebook.com/InstitutefortheStudyofWar" />\n\t<meta property="article:published_time" content="2022-08-15T03:23:00+00:00" />\n\t<meta property="article:modified_time" content="2025-08-29T14:25:42+00:00" />\n\t<meta property="og:image" content="https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_27.jpg" />\n\t<meta property="og:image:width" content="1200" />\n\t<meta property="og:image:height" content="1201" />\n\t<meta property="og:image:type" content="image/jpeg" />\n\t<meta name="author" content="Jennifer Cafarella" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<meta name="twitter:label1" content="Written by" />\n\t<meta name="twitter:data1" content="Jennifer Cafarella" />\n\t<meta name="twitter:label2" content="Est. reading time" />\n\t<meta name="twitter:data2" content="29 minutes" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#article","isPartOf":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/"},"author":{"name":"Jennifer Cafarella","@id":"https://understandingwar.org/#/schema/person/d46f5d4ce050fabd17ded9a74ebe625b"},"headline":"Russian Offensive Campaign Assessment, August 14, 2022","datePublished":"2022-08-15T03:23:00+00:00","dateModified":"2025-08-29T14:25:42+00:00","mainEntityOfPage":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/"},"wordCount":5906,"publisher":{"@id":"https://understandingwar.org/#organization"},"image":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#primaryimage"},"thumbnailUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_27.jpg","inLanguage":"en-US"},{"@type":"WebPage","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/","url":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/","name":"Russian Offensive Campaign Assessment, August 14, 2022 | ISW","isPartOf":{"@id":"https://understandingwar.org/#website"},"primaryImageOfPage":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#primaryimage"},"image":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#primaryimage"},"thumbnailUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_27.jpg","datePublished":"2022-08-15T03:23:00+00:00","dateModified":"2025-08-29T14:25:42+00:00","breadcrumb":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/"]}]},{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#primaryimage","url":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_27.jpg","contentUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_27.jpg","width":1200,"height":1201,"caption":"Institute for the Study of War logo"},{"@type":"BreadcrumbList","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_14-25/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://understandingwar.org/"},{"@type":"ListItem","position":2,"name":"Russian Offensive Campaign Assessment, August 14, 2022"}]},{"@type":"WebSite","@id":"https://understandingwar.org/#website","url":"https://understandingwar.org/","name":"Institute for the Study of War","description":"","publisher":{"@id":"https://understandingwar.org/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://understandingwar.org/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://understandingwar.org/#organization","name":"Understanding War","alternateName":"Institute for the Study of War","url":"https://understandingwar.org/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/#/schema/logo/image/","url":"https://understandingwar.org/wp-content/uploads/2025/08/25-240-07-ISW-Research-Library-Graphic_1080x1080.webp","contentUrl":"https://understandingwar.org/wp-content/uploads/2025/08/25-240-07-ISW-Research-Library-Graphic_1080x1080.webp","width":1080,"height":1080,"caption":"Understanding War"},"image":{"@id":"https://understandingwar.org/#/schema/logo/image/"},"sameAs":["https://www.facebook.com/InstitutefortheStudyofWar"]},{"@type":"Person","@id":"https://understandingwar.org/#/schema/person/d46f5d4ce050fabd17ded9a74ebe625b","name":"Jennifer Cafarella","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/#/schema/person/image/","url":"https://secure.gravatar.com/avatar/95de08882185d6a3b903f08fd02f476fee68e343b76d276daecc14efb242c07c?s=96&d=mm&r=g","contentUrl":"https://secure.gravatar.com/avatar/95de08882185d6a3b903f08fd02f476fee68e343b76d276daecc14efb242c07c?s=96&d=mm&r=g","caption":"Jennifer Cafarella"}}]}</script>\n\t<!-- / Yoast SEO Premium plugin. -->\n\n\n<link rel=\'dns-prefetch\' href=\'//www.google.com\' />\n<link href=\'https://fonts.gstatic.com\' crossorigin rel=\'preconnect\' />\n<link href=\'https://fonts.googleapis.com\' crossorigin rel=\'preconnect\' />\n<style id=\'wp-img-auto-sizes-contain-inline-css\'>\nimg:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}\n/*# sourceURL=wp-img-auto-sizes-contain-inline-css */\n</style>\n<style id=\'wp-block-library-inline-css\'>\n:root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}.has-text-align-center{text-align:center}.has-text-align-left{text-align:left}.has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px;word-wrap:normal!important}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}\n\n/*# sourceURL=wp-block-library-inline-css */\n</style>\n<style id=\'wp-block-navigation-inline-css\'>\n.wp-block-navigation{position:relative}.wp-block-navigation ul{margin-bottom:0;margin-left:0;margin-top:0;padding-left:0}.wp-block-navigation ul,.wp-block-navigation ul li{list-style:none;padding:0}.wp-block-navigation .wp-block-navigation-item{align-items:center;background-color:inherit;display:flex;position:relative}.wp-block-navigation .wp-block-navigation-item .wp-block-navigation__submenu-container:empty{display:none}.wp-block-navigation .wp-block-navigation-item__content{display:block;z-index:1}.wp-block-navigation .wp-block-navigation-item__content.wp-block-navigation-item__content{color:inherit}.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content,.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content:active,.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content:focus{text-decoration:underline}.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content,.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content:active,.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content:focus{text-decoration:line-through}.wp-block-navigation :where(a),.wp-block-navigation :where(a:active),.wp-block-navigation :where(a:focus){text-decoration:none}.wp-block-navigation .wp-block-navigation__submenu-icon{align-self:center;background-color:inherit;border:none;color:currentColor;display:inline-block;font-size:inherit;height:.6em;line-height:0;margin-left:.25em;padding:0;width:.6em}.wp-block-navigation .wp-block-navigation__submenu-icon svg{display:inline-block;stroke:currentColor;height:inherit;margin-top:.075em;width:inherit}.wp-block-navigation{--navigation-layout-justification-setting:flex-start;--navigation-layout-direction:row;--navigation-layout-wrap:wrap;--navigation-layout-justify:flex-start;--navigation-layout-align:center}.wp-block-navigation.is-vertical{--navigation-layout-direction:column;--navigation-layout-justify:initial;--navigation-layout-align:flex-start}.wp-block-navigation.no-wrap{--navigation-layout-wrap:nowrap}.wp-block-navigation.items-justified-center{--navigation-layout-justification-setting:center;--navigation-layout-justify:center}.wp-block-navigation.items-justified-center.is-vertical{--navigation-layout-align:center}.wp-block-navigation.items-justified-right{--navigation-layout-justification-setting:flex-end;--navigation-layout-justify:flex-end}.wp-block-navigation.items-justified-right.is-vertical{--navigation-layout-align:flex-end}.wp-block-navigation.items-justified-space-between{--navigation-layout-justification-setting:space-between;--navigation-layout-justify:space-between}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{align-items:normal;background-color:inherit;color:inherit;display:flex;flex-direction:column;opacity:0;position:absolute;z-index:2}@media not (prefers-reduced-motion){.wp-block-navigation .has-child .wp-block-navigation__submenu-container{transition:opacity .1s linear}}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{height:0;overflow:hidden;visibility:hidden;width:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container>.wp-block-navigation-item>.wp-block-navigation-item__content{display:flex;flex-grow:1;padding:.5em 1em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container>.wp-block-navigation-item>.wp-block-navigation-item__content .wp-block-navigation__submenu-icon{margin-left:auto;margin-right:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation-item__content{margin:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{left:-1px;top:100%}@media (min-width:782px){.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container{left:100%;top:-1px}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container:before{background:#0000;content:"";display:block;height:100%;position:absolute;right:100%;width:.5em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-icon{margin-right:.25em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-icon svg{transform:rotate(-90deg)}}.wp-block-navigation .has-child .wp-block-navigation-submenu__toggle[aria-expanded=true]~.wp-block-navigation__submenu-container,.wp-block-navigation .has-child:not(.open-on-click):hover>.wp-block-navigation__submenu-container,.wp-block-navigation .has-child:not(.open-on-click):not(.open-on-hover-click):focus-within>.wp-block-navigation__submenu-container{height:auto;min-width:200px;opacity:1;overflow:visible;visibility:visible;width:auto}.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container{left:0;top:100%}@media (min-width:782px){.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container{left:100%;top:0}}.wp-block-navigation-submenu{display:flex;position:relative}.wp-block-navigation-submenu .wp-block-navigation__submenu-icon svg{stroke:currentColor}button.wp-block-navigation-item__content{background-color:initial;border:none;color:currentColor;font-family:inherit;font-size:inherit;font-style:inherit;font-weight:inherit;letter-spacing:inherit;line-height:inherit;text-align:left;text-transform:inherit}.wp-block-navigation-submenu__toggle{cursor:pointer}.wp-block-navigation-submenu__toggle[aria-expanded=true]+.wp-block-navigation__submenu-icon>svg,.wp-block-navigation-submenu__toggle[aria-expanded=true]>svg{transform:rotate(180deg)}.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle{padding-left:0;padding-right:.85em}.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle+.wp-block-navigation__submenu-icon{margin-left:-.6em;pointer-events:none}.wp-block-navigation-item.open-on-click button.wp-block-navigation-item__content:not(.wp-block-navigation-submenu__toggle){padding:0}.wp-block-navigation .wp-block-page-list,.wp-block-navigation__container,.wp-block-navigation__responsive-close,.wp-block-navigation__responsive-container,.wp-block-navigation__responsive-container-content,.wp-block-navigation__responsive-dialog{gap:inherit}:where(.wp-block-navigation.has-background .wp-block-navigation-item a:not(.wp-element-button)),:where(.wp-block-navigation.has-background .wp-block-navigation-submenu a:not(.wp-element-button)){padding:.5em 1em}:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-item a:not(.wp-element-button)),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-submenu a:not(.wp-element-button)),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-submenu button.wp-block-navigation-item__content),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-pages-list__item button.wp-block-navigation-item__content){padding:.5em 1em}.wp-block-navigation.items-justified-right .wp-block-navigation__container .has-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-right .wp-block-page-list>.has-child .wp-block-navigatio

In [9]:
data = data.sort_values(by=['date'])

In [10]:
data

,id,date,short_url,title,text_title,full_url,html_content
1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
...,...,...,...,...,...,...,...
736,737,2026-02-25,2026_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
827,828,2026-02-26,2026_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
1012,1013,2026-02-27,2026_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
470,471,2026-02-28,2026_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
1188,1189,2026-03-01,2026_03_01,"Russian Offensive Campaign Assessment, March 1...","Russian Offensive Campaign Assessment, March 1...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."

In [11]:
from IPython.core.display import HTML, display
display(HTML(data['html_content'][0]))

/var/folders/k6/9kclm4r55wn8573ccdyzgj1m0000gn/T/ipykernel_1495/2979927905.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import HTML, display

1. Remove HTML Content

In [12]:
def remove_names_and_dates(page_html_text):
    parsed_html = BeautifulSoup(page_html_text)
    p_lines = parsed_html.findAll('p')
    
    min_sentense_word_count = 13
    p_index = 0
    
    for p_line in p_lines:
        
        strong_lines = p_line.findAll('strong')
        if not strong_lines:
            continue 
            
        for s in strong_lines:
            if (len(s.text.split(" ")) >= min_sentense_word_count ):
                break
            else:
                p_index += 1
                
                continue
            break
            
        for i in range(0,p_index):
            page_html_text = page_html_text.replace(str(p_lines[i]),"")
            
        return page_html_text

In [13]:
data['html_content_v2'] = data['html_content'].apply(lambda x: remove_names_and_dates(x))

In [14]:
data.head()

,id,date,short_url,title,text_title,full_url,html_content,html_content_v2
1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."
1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n..."

In [15]:
data['html_content_v2'][0]

'<!DOCTYPE html>\n<html lang="en-US">\n<head>\n\t<meta charset="UTF-8">\n\t<meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n\t<!-- This site is optimized with the Yoast SEO Premium plugin v27.0 (Yoast SEO v27.0) - https://yoast.com/product/yoast-seo-premium-wordpress/ -->\n\t<title>Russian Offensive Campaign Assessment, November 5, 2022 | ISW</title>\n\t<link rel="canonical" href="https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/" />\n\t<meta property="og:locale" content="en_US" />\n\t<meta property="og:type" content="article" />\n\t<meta property="og:title" content="Russian Offensive Campaign Assessment, November 5, 2022" />\n\t<meta property="og:description" content="Wagner Group financier Yevgeny Prigozhin seeks to obfuscate his efforts to strengthen his independent power base with an appeal to the concept of Russia’s historic unity. Prigozhin provided a vague response to a media inquiry regarding his recent visit to Kursk Oblast on Russia’s Unity Day (November 4), during which he had indirectly implied that Wagner forces are involved in upholding Russia’s unity. Prigozhin stated that Russian people, businesses, government, and army need to come together to fight for Russia’s sovereignty and its great future while deflecting from the journalist’s question regarding Prigozhin’s reported meeting with Kursk businessmen about the organization of an unspecified people’s militia – outside of formal Russian military command structures. Prigozhin also noted that Russia has all the ingredients to achieve its goals including a strong president, cohesive army, and great nationhood, which he concluded with an out-of-place greeting from Wagner fighters. Prigozhin later claimed in a follow up media response that his “independence” does not contradict Russian President Vladimir Putin’s politics as some audiences have interpreted." />\n\t<meta property="og:url" content="https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/" />\n\t<meta property="og:site_name" content="Institute for the Study of War" />\n\t<meta property="article:publisher" content="https://www.facebook.com/InstitutefortheStudyofWar" />\n\t<meta property="article:published_time" content="2022-11-06T01:35:00+00:00" />\n\t<meta property="article:modified_time" content="2025-08-26T20:37:51+00:00" />\n\t<meta property="og:image" content="https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg" />\n\t<meta property="og:image:width" content="1200" />\n\t<meta property="og:image:height" content="1201" />\n\t<meta property="og:image:type" content="image/jpeg" />\n\t<meta name="author" content="Jennifer Cafarella" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<meta name="twitter:label1" content="Written by" />\n\t<meta name="twitter:data1" content="Jennifer Cafarella" />\n\t<meta name="twitter:label2" content="Est. reading time" />\n\t<meta name="twitter:data2" content="16 minutes" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#article","isPartOf":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/"},"author":{"name":"Jennifer Cafarella","@id":"https://understandingwar.org/#/schema/person/d46f5d4ce050fabd17ded9a74ebe625b"},"headline":"Russian Offensive Campaign Assessment, November 5, 2022","datePublished":"2022-11-06T01:35:00+00:00","dateModified":"2025-08-26T20:37:51+00:00","mainEntityOfPage":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/"},"wordCount":4613,"publisher":{"@id":"https://understandingwar.org/#organization"},"image":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage"},"thumbnailUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","inLanguage":"en-US"},{"@type":"WebPage","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/","url":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/","name":"Russian Offensive Campaign Assessment, November 5, 2022 | ISW","isPartOf":{"@id":"https://understandingwar.org/#website"},"primaryImageOfPage":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage"},"image":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage"},"thumbnailUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","datePublished":"2022-11-06T01:35:00+00:00","dateModified":"2025-08-26T20:37:51+00:00","breadcrumb":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/"]}]},{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage","url":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","contentUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","width":1200,"height":1201},{"@type":"BreadcrumbList","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://understandingwar.org/"},{"@type":"ListItem","position":2,"name":"Russian Offensive Campaign Assessment, November 5, 2022"}]},{"@type":"WebSite","@id":"https://understandingwar.org/#website","url":"https://understandingwar.org/","name":"Institute for the Study of War","description":"","publisher":{"@id":"https://understandingwar.org/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://understandingwar.org/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://understandingwar.org/#organization","name":"Understanding War","alternateName":"Institute for the Study of War","url":"https://understandingwar.org/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/#/schema/logo/image/","url":"https://understandingwar.org/wp-content/uploads/2025/08/25-240-07-ISW-Research-Library-Graphic_1080x1080.webp","contentUrl":"https://understandingwar.org/wp-content/uploads/2025/08/25-240-07-ISW-Research-Library-Graphic_1080x1080.webp","width":1080,"height":1080,"caption":"Understanding War"},"image":{"@id":"https://understandingwar.org/#/schema/logo/image/"},"sameAs":["https://www.facebook.com/InstitutefortheStudyofWar"]},{"@type":"Person","@id":"https://understandingwar.org/#/schema/person/d46f5d4ce050fabd17ded9a74ebe625b","name":"Jennifer Cafarella","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/#/schema/person/image/","url":"https://secure.gravatar.com/avatar/95de08882185d6a3b903f08fd02f476fee68e343b76d276daecc14efb242c07c?s=96&d=mm&r=g","contentUrl":"https://secure.gravatar.com/avatar/95de08882185d6a3b903f08fd02f476fee68e343b76d276daecc14efb242c07c?s=96&d=mm&r=g","caption":"Jennifer Cafarella"}}]}</script>\n\t<!-- / Yoast SEO Premium plugin. -->\n\n\n<link rel=\'dns-prefetch\' href=\'//www.google.com\' />\n<link href=\'https://fonts.gstatic.com\' crossorigin rel=\'preconnect\' />\n<link href=\'https://fonts.googleapis.com\' crossorigin rel=\'preconnect\' />\n<style id=\'wp-img-auto-sizes-contain-inline-css\'>\nimg:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}\n/*# sourceURL=wp-img-auto-sizes-contain-inline-css */\n</style>\n<style id=\'wp-block-library-inline-css\'>\n:root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}.has-text-align-center{text-align:center}.has-text-align-left{text-align:left}.has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px;word-wrap:normal!important}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}\n\n/*# sourceURL=wp-block-library-inline-css */\n</style>\n<style id=\'wp-block-navigation-inline-css\'>\n.wp-block-navigation{position:relative}.wp-block-navigation ul{margin-bottom:0;margin-left:0;margin-top:0;padding-left:0}.wp-block-navigation ul,.wp-block-navigation ul li{list-style:none;padding:0}.wp-block-navigation .wp-block-navigation-item{align-items:center;background-color:inherit;display:flex;position:relative}.wp-block-navigation .wp-block-navigation-item .wp-block-navigation__submenu-container:empty{display:none}.wp-block-navigation .wp-block-navigation-item__content{display:block;z-index:1}.wp-block-navigation .wp-block-navigation-item__content.wp-block-navigation-item__content{color:inherit}.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content,.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content:active,.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content:focus{text-decoration:underline}.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content,.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content:active,.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content:focus{text-decoration:line-through}.wp-block-navigation :where(a),.wp-block-navigation :where(a:active),.wp-block-navigation :where(a:focus){text-decoration:none}.wp-block-navigation .wp-block-navigation__submenu-icon{align-self:center;background-color:inherit;border:none;color:currentColor;display:inline-block;font-size:inherit;height:.6em;line-height:0;margin-left:.25em;padding:0;width:.6em}.wp-block-navigation .wp-block-navigation__submenu-icon svg{display:inline-block;stroke:currentColor;height:inherit;margin-top:.075em;width:inherit}.wp-block-navigation{--navigation-layout-justification-setting:flex-start;--navigation-layout-direction:row;--navigation-layout-wrap:wrap;--navigation-layout-justify:flex-start;--navigation-layout-align:center}.wp-block-navigation.is-vertical{--navigation-layout-direction:column;--navigation-layout-justify:initial;--navigation-layout-align:flex-start}.wp-block-navigation.no-wrap{--navigation-layout-wrap:nowrap}.wp-block-navigation.items-justified-center{--navigation-layout-justification-setting:center;--navigation-layout-justify:center}.wp-block-navigation.items-justified-center.is-vertical{--navigation-layout-align:center}.wp-block-navigation.items-justified-right{--navigation-layout-justification-setting:flex-end;--navigation-layout-justify:flex-end}.wp-block-navigation.items-justified-right.is-vertical{--navigation-layout-align:flex-end}.wp-block-navigation.items-justified-space-between{--navigation-layout-justification-setting:space-between;--navigation-layout-justify:space-between}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{align-items:normal;background-color:inherit;color:inherit;display:flex;flex-direction:column;opacity:0;position:absolute;z-index:2}@media not (prefers-reduced-motion){.wp-block-navigation .has-child .wp-block-navigation__submenu-container{transition:opacity .1s linear}}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{height:0;overflow:hidden;visibility:hidden;width:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container>.wp-block-navigation-item>.wp-block-navigation-item__content{display:flex;flex-grow:1;padding:.5em 1em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container>.wp-block-navigation-item>.wp-block-navigation-item__content .wp-block-navigation__submenu-icon{margin-left:auto;margin-right:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation-item__content{margin:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{left:-1px;top:100%}@media (min-width:782px){.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container{left:100%;top:-1px}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container:before{background:#0000;content:"";display:block;height:100%;position:absolute;right:100%;width:.5em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-icon{margin-right:.25em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-icon svg{transform:rotate(-90deg)}}.wp-block-navigation .has-child .wp-block-navigation-submenu__toggle[aria-expanded=true]~.wp-block-navigation__submenu-container,.wp-block-navigation .has-child:not(.open-on-click):hover>.wp-block-navigation__submenu-container,.wp-block-navigation .has-child:not(.open-on-click):not(.open-on-hover-click):focus-within>.wp-block-navigation__submenu-container{height:auto;min-width:200px;opacity:1;overflow:visible;visibility:visible;width:auto}.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container{left:0;top:100%}@media (min-width:782px){.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container{left:100%;top:0}}.wp-block-navigation-submenu{display:flex;position:relative}.wp-block-navigation-submenu .wp-block-navigation__submenu-icon svg{stroke:currentColor}button.wp-block-navigation-item__content{background-color:initial;border:none;color:currentColor;font-family:inherit;font-size:inherit;font-style:inherit;font-weight:inherit;letter-spacing:inherit;line-height:inherit;text-align:left;text-transform:inherit}.wp-block-navigation-submenu__toggle{cursor:pointer}.wp-block-navigation-submenu__toggle[aria-expanded=true]+.wp-block-navigation__submenu-icon>svg,.wp-block-navigation-submenu__toggle[aria-expanded=true]>svg{transform:rotate(180deg)}.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle{padding-left:0;padding-right:.85em}.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle+.wp-block-navigation__submenu-icon{margin-left:-.6em;pointer-events:none}.wp-block-navigation-item.open-on-click button.wp-block-navigation-item__content:not(.wp-block-navigation-submenu__toggle){padding:0}.wp-block-navigation .wp-block-page-list,.wp-block-navigation__container,.wp-block-navigation__responsive-close,.wp-block-navigation__responsive-container,.wp-block-navigation__responsive-container-content,.wp-block-navigation__responsive-dialog{gap:inherit}:where(.wp-block-navigation.has-background .wp-block-navigation-item a:not(.wp-element-button)),:where(.wp-block-navigation.has-background .wp-block-navigation-submenu a:not(.wp-element-button)){padding:.5em 1em}:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-item a:not(.wp-element-button)),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-submenu a:not(.wp-element-button)),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-submenu button.wp-block-navigation-item__content),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-pages-list__item button.wp-block-navigation-item__content){padding:.5em 1em}.wp-block-navigation.items-justified-right .wp-block-navigation__container .has-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-right .wp-block-page-list>.has-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-space-between .wp-block-page-list>.has-child:last-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-space-between>.wp-block-navigation__container>.has-child:last-child .wp-block-navigation__submenu-container{left:auto;right:0}.wp-block-navigation.items-justified-right .wp-block-navigation__container .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-right .wp-block-page-list>.has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container,.wp-block-nav

2. Remove all numbers

In [17]:
import re

pattern = "\[(\d+)\]"


data['html_content_v3'] = data['html_content_v2'].apply(lambda x: re.sub(pattern,'',str(x)))

In [18]:
data['html_content_v3'][0]

'<!DOCTYPE html>\n<html lang="en-US">\n<head>\n\t<meta charset="UTF-8">\n\t<meta name=\'robots\' content=\'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1\' />\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n\t<!-- This site is optimized with the Yoast SEO Premium plugin v27.0 (Yoast SEO v27.0) - https://yoast.com/product/yoast-seo-premium-wordpress/ -->\n\t<title>Russian Offensive Campaign Assessment, November 5, 2022 | ISW</title>\n\t<link rel="canonical" href="https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/" />\n\t<meta property="og:locale" content="en_US" />\n\t<meta property="og:type" content="article" />\n\t<meta property="og:title" content="Russian Offensive Campaign Assessment, November 5, 2022" />\n\t<meta property="og:description" content="Wagner Group financier Yevgeny Prigozhin seeks to obfuscate his efforts to strengthen his independent power base with an appeal to the concept of Russia’s historic unity. Prigozhin provided a vague response to a media inquiry regarding his recent visit to Kursk Oblast on Russia’s Unity Day (November 4), during which he had indirectly implied that Wagner forces are involved in upholding Russia’s unity. Prigozhin stated that Russian people, businesses, government, and army need to come together to fight for Russia’s sovereignty and its great future while deflecting from the journalist’s question regarding Prigozhin’s reported meeting with Kursk businessmen about the organization of an unspecified people’s militia – outside of formal Russian military command structures. Prigozhin also noted that Russia has all the ingredients to achieve its goals including a strong president, cohesive army, and great nationhood, which he concluded with an out-of-place greeting from Wagner fighters. Prigozhin later claimed in a follow up media response that his “independence” does not contradict Russian President Vladimir Putin’s politics as some audiences have interpreted." />\n\t<meta property="og:url" content="https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/" />\n\t<meta property="og:site_name" content="Institute for the Study of War" />\n\t<meta property="article:publisher" content="https://www.facebook.com/InstitutefortheStudyofWar" />\n\t<meta property="article:published_time" content="2022-11-06T01:35:00+00:00" />\n\t<meta property="article:modified_time" content="2025-08-26T20:37:51+00:00" />\n\t<meta property="og:image" content="https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg" />\n\t<meta property="og:image:width" content="1200" />\n\t<meta property="og:image:height" content="1201" />\n\t<meta property="og:image:type" content="image/jpeg" />\n\t<meta name="author" content="Jennifer Cafarella" />\n\t<meta name="twitter:card" content="summary_large_image" />\n\t<meta name="twitter:label1" content="Written by" />\n\t<meta name="twitter:data1" content="Jennifer Cafarella" />\n\t<meta name="twitter:label2" content="Est. reading time" />\n\t<meta name="twitter:data2" content="16 minutes" />\n\t<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#article","isPartOf":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/"},"author":{"name":"Jennifer Cafarella","@id":"https://understandingwar.org/#/schema/person/d46f5d4ce050fabd17ded9a74ebe625b"},"headline":"Russian Offensive Campaign Assessment, November 5, 2022","datePublished":"2022-11-06T01:35:00+00:00","dateModified":"2025-08-26T20:37:51+00:00","mainEntityOfPage":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/"},"wordCount":4613,"publisher":{"@id":"https://understandingwar.org/#organization"},"image":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage"},"thumbnailUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","inLanguage":"en-US"},{"@type":"WebPage","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/","url":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/","name":"Russian Offensive Campaign Assessment, November 5, 2022 | ISW","isPartOf":{"@id":"https://understandingwar.org/#website"},"primaryImageOfPage":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage"},"image":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage"},"thumbnailUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","datePublished":"2022-11-06T01:35:00+00:00","dateModified":"2025-08-26T20:37:51+00:00","breadcrumb":{"@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/"]}]},{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#primaryimage","url":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","contentUrl":"https://understandingwar.org/wp-content/uploads/2025/04/ISW20LOGO202_59.jpg","width":1200,"height":1201},{"@type":"BreadcrumbList","@id":"https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment_5-24/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://understandingwar.org/"},{"@type":"ListItem","position":2,"name":"Russian Offensive Campaign Assessment, November 5, 2022"}]},{"@type":"WebSite","@id":"https://understandingwar.org/#website","url":"https://understandingwar.org/","name":"Institute for the Study of War","description":"","publisher":{"@id":"https://understandingwar.org/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://understandingwar.org/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://understandingwar.org/#organization","name":"Understanding War","alternateName":"Institute for the Study of War","url":"https://understandingwar.org/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/#/schema/logo/image/","url":"https://understandingwar.org/wp-content/uploads/2025/08/25-240-07-ISW-Research-Library-Graphic_1080x1080.webp","contentUrl":"https://understandingwar.org/wp-content/uploads/2025/08/25-240-07-ISW-Research-Library-Graphic_1080x1080.webp","width":1080,"height":1080,"caption":"Understanding War"},"image":{"@id":"https://understandingwar.org/#/schema/logo/image/"},"sameAs":["https://www.facebook.com/InstitutefortheStudyofWar"]},{"@type":"Person","@id":"https://understandingwar.org/#/schema/person/d46f5d4ce050fabd17ded9a74ebe625b","name":"Jennifer Cafarella","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://understandingwar.org/#/schema/person/image/","url":"https://secure.gravatar.com/avatar/95de08882185d6a3b903f08fd02f476fee68e343b76d276daecc14efb242c07c?s=96&d=mm&r=g","contentUrl":"https://secure.gravatar.com/avatar/95de08882185d6a3b903f08fd02f476fee68e343b76d276daecc14efb242c07c?s=96&d=mm&r=g","caption":"Jennifer Cafarella"}}]}</script>\n\t<!-- / Yoast SEO Premium plugin. -->\n\n\n<link rel=\'dns-prefetch\' href=\'//www.google.com\' />\n<link href=\'https://fonts.gstatic.com\' crossorigin rel=\'preconnect\' />\n<link href=\'https://fonts.googleapis.com\' crossorigin rel=\'preconnect\' />\n<style id=\'wp-img-auto-sizes-contain-inline-css\'>\nimg:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}\n/*# sourceURL=wp-img-auto-sizes-contain-inline-css */\n</style>\n<style id=\'wp-block-library-inline-css\'>\n:root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}.has-text-align-center{text-align:center}.has-text-align-left{text-align:left}.has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px;word-wrap:normal!important}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}\n\n/*# sourceURL=wp-block-library-inline-css */\n</style>\n<style id=\'wp-block-navigation-inline-css\'>\n.wp-block-navigation{position:relative}.wp-block-navigation ul{margin-bottom:0;margin-left:0;margin-top:0;padding-left:0}.wp-block-navigation ul,.wp-block-navigation ul li{list-style:none;padding:0}.wp-block-navigation .wp-block-navigation-item{align-items:center;background-color:inherit;display:flex;position:relative}.wp-block-navigation .wp-block-navigation-item .wp-block-navigation__submenu-container:empty{display:none}.wp-block-navigation .wp-block-navigation-item__content{display:block;z-index:1}.wp-block-navigation .wp-block-navigation-item__content.wp-block-navigation-item__content{color:inherit}.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content,.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content:active,.wp-block-navigation.has-text-decoration-underline .wp-block-navigation-item__content:focus{text-decoration:underline}.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content,.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content:active,.wp-block-navigation.has-text-decoration-line-through .wp-block-navigation-item__content:focus{text-decoration:line-through}.wp-block-navigation :where(a),.wp-block-navigation :where(a:active),.wp-block-navigation :where(a:focus){text-decoration:none}.wp-block-navigation .wp-block-navigation__submenu-icon{align-self:center;background-color:inherit;border:none;color:currentColor;display:inline-block;font-size:inherit;height:.6em;line-height:0;margin-left:.25em;padding:0;width:.6em}.wp-block-navigation .wp-block-navigation__submenu-icon svg{display:inline-block;stroke:currentColor;height:inherit;margin-top:.075em;width:inherit}.wp-block-navigation{--navigation-layout-justification-setting:flex-start;--navigation-layout-direction:row;--navigation-layout-wrap:wrap;--navigation-layout-justify:flex-start;--navigation-layout-align:center}.wp-block-navigation.is-vertical{--navigation-layout-direction:column;--navigation-layout-justify:initial;--navigation-layout-align:flex-start}.wp-block-navigation.no-wrap{--navigation-layout-wrap:nowrap}.wp-block-navigation.items-justified-center{--navigation-layout-justification-setting:center;--navigation-layout-justify:center}.wp-block-navigation.items-justified-center.is-vertical{--navigation-layout-align:center}.wp-block-navigation.items-justified-right{--navigation-layout-justification-setting:flex-end;--navigation-layout-justify:flex-end}.wp-block-navigation.items-justified-right.is-vertical{--navigation-layout-align:flex-end}.wp-block-navigation.items-justified-space-between{--navigation-layout-justification-setting:space-between;--navigation-layout-justify:space-between}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{align-items:normal;background-color:inherit;color:inherit;display:flex;flex-direction:column;opacity:0;position:absolute;z-index:2}@media not (prefers-reduced-motion){.wp-block-navigation .has-child .wp-block-navigation__submenu-container{transition:opacity .1s linear}}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{height:0;overflow:hidden;visibility:hidden;width:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container>.wp-block-navigation-item>.wp-block-navigation-item__content{display:flex;flex-grow:1;padding:.5em 1em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container>.wp-block-navigation-item>.wp-block-navigation-item__content .wp-block-navigation__submenu-icon{margin-left:auto;margin-right:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation-item__content{margin:0}.wp-block-navigation .has-child .wp-block-navigation__submenu-container{left:-1px;top:100%}@media (min-width:782px){.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container{left:100%;top:-1px}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container:before{background:#0000;content:"";display:block;height:100%;position:absolute;right:100%;width:.5em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-icon{margin-right:.25em}.wp-block-navigation .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-icon svg{transform:rotate(-90deg)}}.wp-block-navigation .has-child .wp-block-navigation-submenu__toggle[aria-expanded=true]~.wp-block-navigation__submenu-container,.wp-block-navigation .has-child:not(.open-on-click):hover>.wp-block-navigation__submenu-container,.wp-block-navigation .has-child:not(.open-on-click):not(.open-on-hover-click):focus-within>.wp-block-navigation__submenu-container{height:auto;min-width:200px;opacity:1;overflow:visible;visibility:visible;width:auto}.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container{left:0;top:100%}@media (min-width:782px){.wp-block-navigation.has-background .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container{left:100%;top:0}}.wp-block-navigation-submenu{display:flex;position:relative}.wp-block-navigation-submenu .wp-block-navigation__submenu-icon svg{stroke:currentColor}button.wp-block-navigation-item__content{background-color:initial;border:none;color:currentColor;font-family:inherit;font-size:inherit;font-style:inherit;font-weight:inherit;letter-spacing:inherit;line-height:inherit;text-align:left;text-transform:inherit}.wp-block-navigation-submenu__toggle{cursor:pointer}.wp-block-navigation-submenu__toggle[aria-expanded=true]+.wp-block-navigation__submenu-icon>svg,.wp-block-navigation-submenu__toggle[aria-expanded=true]>svg{transform:rotate(180deg)}.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle{padding-left:0;padding-right:.85em}.wp-block-navigation-item.open-on-click .wp-block-navigation-submenu__toggle+.wp-block-navigation__submenu-icon{margin-left:-.6em;pointer-events:none}.wp-block-navigation-item.open-on-click button.wp-block-navigation-item__content:not(.wp-block-navigation-submenu__toggle){padding:0}.wp-block-navigation .wp-block-page-list,.wp-block-navigation__container,.wp-block-navigation__responsive-close,.wp-block-navigation__responsive-container,.wp-block-navigation__responsive-container-content,.wp-block-navigation__responsive-dialog{gap:inherit}:where(.wp-block-navigation.has-background .wp-block-navigation-item a:not(.wp-element-button)),:where(.wp-block-navigation.has-background .wp-block-navigation-submenu a:not(.wp-element-button)){padding:.5em 1em}:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-item a:not(.wp-element-button)),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-submenu a:not(.wp-element-button)),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-navigation-submenu button.wp-block-navigation-item__content),:where(.wp-block-navigation .wp-block-navigation__submenu-container .wp-block-pages-list__item button.wp-block-navigation-item__content){padding:.5em 1em}.wp-block-navigation.items-justified-right .wp-block-navigation__container .has-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-right .wp-block-page-list>.has-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-space-between .wp-block-page-list>.has-child:last-child .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-space-between>.wp-block-navigation__container>.has-child:last-child .wp-block-navigation__submenu-container{left:auto;right:0}.wp-block-navigation.items-justified-right .wp-block-navigation__container .has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container,.wp-block-navigation.items-justified-right .wp-block-page-list>.has-child .wp-block-navigation__submenu-container .wp-block-navigation__submenu-container,.wp-block-nav

3.Remove list of references

In [19]:
data['html_content_v4'] = data['html_content_v3'].apply(lambda x: BeautifulSoup(x).text)

In [20]:
data['html_content_v4'][0]

"\n\n\n\n\n\n\nRussian Offensive Campaign Assessment, November 5, 2022 | ISW\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nOptions\n\n\n\t\t\t\tDOWNLOAD PAGE\n\t\t\t  \nPRINT PAGE\n\nShare\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSkip to contentSkip to Content \n\n\n\n\n\n \n \n\n\nDonate \nMenu \n\n\n\n\n\n\n\n \nMenu \nAbout ISW\n\n\n\nAbout ISW\n\n\n\nOur Capabilities\nISW’s Comparative Advantage\n\n\nOur History\nImproving the National Security Debate\n\n\n\n\nWho We Are\nMeet the Team\n\n\nCareers\nJoin the Mission\n\n\nOpen Positions\n\n\n\n\n\n\n\nMAP ROOM\nISW produces the world’s premier open-source conflict maps\n  SEE MAPS\n\n\n\n\n\n\n\n\nAnalysis\n\n\n\nAnalysis\nThe General Jack Keane Center for National Security\n\n\n\nMap Room\nDive into ISW's Complete Map Catalog\n\n\nBriefing Room\nVideos, Podcasts, and Interactive Content\n\n\nResearch Library\nBrowse ISW's Entire Body of Work\n\n\n\nTEAMS/PORTFOLIOS\n\nRussia & Ukraine\n\n\nMiddle East\n\n\nChina & Taiwan\n\n\nDefense of Europe\n\n\n\n\nAdversary Entente\n\n\nContemporary & Future War\n\n\nGeospatial Intelligence\n\n\nCognitive Warfare\n\n\n\n\n\n\n\nEducation\n\n\n\nEducation\nThe General David H. Petraeus Center for Emerging Leaders\n\n\n\nHertog War Studies\nISW’s Premier Educational Program for Undergraduates\n\n\n\n\nFellowships\nEnrichment and Advancement Opportunities for Entry-Level and Mid-Career Professionals\n\n\nInternships\nLaunch your Career at ISW with an Internship in Open-Source Intelligence, Geospatial Intelligence, Cognitive Warfare, or Communications\n\n\n\n\n\n\n\nResearch Library\nBrowse ISW’s published work, curated for maximum searchability\n  view insights\n\n\n\n\n\n\n\n\nGet Involved\n\n\n\nGet Involved\nJoin the ISW Community and Help Us Safeguard America’s Security\n\n\n\nDonate\nYour Donations Keep ISW Independent, Nonpartisan, and Objective\n\n\n\n\nPlanned Giving\nSecure Your Legacy and Strengthen Future Generations\n\n\n\n\nOur Partners\nPartnering With ISW Makes a Direct Impact on America’s Security and Future Leaders\n\n\n\n\n\n\n\nNewsroom\n \n\n\nDonate \n\n\n\n\n\n\nRussia & Ukraine\nUkraine\nRussian Offensive Campaign Assessment\n\nRussian Offensive Campaign Assessment, November 5, 2022\nNovember 6, 2022\n\nJump to\n\n\n\n\n\n\nPrevious\nNext\n\nRussian Offensive Campaign Assessment, November 5, 2022\n\xa0Karolina Hird, Kateryna Stepanenko, Riley Bailey, Angela Howard, and Mason Clark\nNovember 5, 6:30 pm ET\nClick\xa0here\xa0to see ISW’s interactive map of the Russian invasion of Ukraine. This map is updated daily alongside the static maps present in this report.\nWagner Group financier Yevgeny Prigozhin seeks to obfuscate his efforts to strengthen his independent power base with an appeal to the concept of Russia’s historic unity.\xa0Prigozhin provided a vague response to a media inquiry regarding his recent visit to Kursk Oblast on Russia’s Unity Day (November 4), during which he had indirectly implied that Wagner forces are involved in upholding Russia’s unity.\xa0Prigozhin stated that Russian people, businesses, government, and army need to come together to fight for Russia’s sovereignty and its great future while deflecting from the journalist’s question regarding Prigozhin’s reported meeting with Kursk businessmen about the organization of an unspecified people’s militia – outside of formal Russian military command structures. Prigozhin also noted that Russia has all the ingredients to achieve its goals including a strong president, cohesive army, and great nationhood, which he concluded with an out-of-place greeting from Wagner fighters. Prigozhin later claimed in a follow up media response that his “independence” does not contradict Russian President Vladimir Putin’s politics as some audiences have interpreted.\nPrigozhin’s rather sarcastic statements have several underlying implications for his perception of his power within Russia. ISW previously reported that Kursk Oblast officials announced the construction of second and third lines of defenses in the region, and if Prigozhin’s meeting with local businessmen took place, may indicate that he is attempting to expand his influence in the region.\xa0Prigozhin’s comment on Russia’s “cohesive army” next to Putin was likely thinly-veiled sarcasm, given that Prigozhin has repeatedly criticized the Russian Armed Forces on numerous occasions.\xa0Prigozhin also directly recognized that he is an independent entity, which as ISW previously assessed, relieves him of some obligations to the Kremlin and the Russian Ministry of Defense (MoD).\xa0Putin’s dependency on Prigozhin’s forces around Bakhmut also allows Prigozhin privileges such as voicing his criticisms of the Kremlin or the Russian Armed Forces without significant ramifications. Prigozhin has also coincidentally opened his Wagner Center in St. Petersburg on Russia’s Unity Day.\xa0However, Prigozhin is notably shielding his efforts to build an independent power base and shape the conduct of Russia’s invasion of Ukraine with language focused on Russian Unity – likely both to appeal to Russian nationalists and civilians and to deflect criticism of his fairly overt efforts to build an independent power base.\nPrigozhin continues to rely on ineffective convicts to staff his forces.\xa0Prigozhin declined to comment on a reporter’s question regarding ongoing recruitment drives at Krasnoyarsk Krai penal colonies, despite previously openly discussing prisoner participation in the war with Russian outlets like\xa0RiaFan.\xa0Russian opposition outlet\xa0The Insider,\xa0however, found that over 500 prisoners recruited into Wagner units have died in the past two months.\xa0The publication added that Wagner lost between 800 and 1,000 mercenaries in Ukraine, indicating convicts comprise a large proportion of Wagner’s forces in Ukraine. Ukrainian intelligence officials also previously reported that many prisoners suffering from infectious diseases infected Wagner troops, to which Prigozhin responded that he does not discriminate on the basis of illness.\nIranian Foreign Minister Hossein Amir-Abdollahian confirmed that Iran sent Russia combat drones.\xa0Amir-Abdollahian stated on November 5 that Iran “gave a limited number of drones to Russia months before” the war in Ukraine.\xa0Amir-Abdollahian also claimed that if Ukrainian officials could prove that the Russian military has used Iranian-made drones in Ukraine then Iranian officials would “not be indifferent” to the concern – falsely and ridiculously implying that Russia has not used the drones that he admitted Iran has provided.\xa0Iran’s confirmation of the drone shipments further supports ISW’s previous assessments that Russia is sourcing Iranian-made weapons systems to address the depletion of its high-precision munitions arsenal.\xa0ISW previously assessed that Iran is likely already exploiting Russian reliance on these Iranian-made weapons systems to request Russian assistance with its nuclear program.\xa0The nuclear assistance requests and the recognition of the drone shipments are both indicators that Iranian officials may intend to more clearly establish an explicit bilateral security relationship with Russia in which they are more equal partners.\nFormer Donetsk People’s Republic (DNR) Security Minister and current DNR military commander Aleksandr Khodakovsky claimed on November 5 that Russian friendly fire may have caused up to 60% of total Russian losses since the end of Russian offensive operations in Mariupol in mid-May.\xa0Even if this statistic is exaggerated, the fact that a Russian commander is publicly speculating on such a damning indicator of Russian and proxy competency indicates the deep challenges Russian forces face. Friendly fire typically does account for a limited number of losses in war but ordinarily nowhere near 60% of total casualties, which demonstrates a lack of communication and command and control coordination between Russian forces. Russian and Ukrainian sources also reported that a Russian rotation returning to its base near Pavlivka, Donetsk Oblast on November 5 drove into a ditch constructed by army subcontractors without prior discussion or warning, further demonstrating a widespread lack of cross-training and coordination between Russian troops.\xa0The frequent replacement of Russian military leaders, promotion of inexperienced soldiers, and cobbled-together Russian force composition including Russian contract soldiers, Russian mobilized soldiers, DNR and Luhansk People’s Republic (LNR) forces, and Wagner Group forces exacerbate the fragmented nature of the Russian chain of command and ineffectiveness of Russian forces and likely contributes to frequent friendly fire incidents.\nKey Takeaways\n\nWagner Group financier Yevheniy Prigozhin seeks to obfuscate his efforts to strengthen his independent power base with an appeal to the concept of Russia’s historic unity.\nIranian Foreign Minister Hossein Amir-Abdollahian confirmed that Iran began providing Russia drones before February 24, but strangely denied that Russian forces have used them in combat.\nDNR military commander Aleksandr Khodakovsky claimed that Russian friendly fire may have caused up to 60% of total Russian losses since mid-May.\nUkrainian troops reportedly continued counteroffensives along the Svatove-Kreminna line.\nRussian forces continued to set up defensive positions along the Dnipro River.\nUkrainian forces continued to target Russian logistics and transportation in Kherson Oblast.\nRussian forces continued to attack around Bakhmut and claimed unspecified advances.\nRussian forces continued unsuccessful offensive operations in the Avdiivka-Donetsk City area and in western Donetsk.\nContinued poor conditions for mobilized soldiers catalyzed a large-scale protest in Kazan.\nUnknown actors reportedly attempted to assassinate high-profile Donetsk People’s Republic (DNR) Supreme Court Judge Aleksandr Nikulin.\nRussia continues to deploy personnel to staff administrative positions in occupied areas.\nRussian forces continued forced evacuations in Kherson Oblast. Over 80% of Kherson residents reportedly have evacuated.\n\n\n\nWe do not report in detail on Russian war crimes because those activities are well-covered in Western media and do not directly affect the military operations we are assessing and forecasting. We will continue to evaluate and report on the effects of these criminal activities on the Ukrainian military and population and specifically on combat in Ukrainian urban areas. We utterly condemn these Russian violations of the laws of armed conflict, Geneva Conventions, and humanity even though we do not describe them in these reports.\n\n\nUkrainian Counteroffensives—Southern and Eastern Ukraine\nRussian Main Effort—Eastern Ukraine (comprised of one subordinate and two supporting efforts);\nRussian Subordinate Main Effort—Capture the entirety of Donetsk Oblast\nRussian Supporting Effort—Southern Axis\nRussian Mobilization and Force Generation Efforts\nActivities in Russian-occupied Areas\n\nUkrainian Counteroffensives\xa0(Ukrainian efforts to liberate Russian-occupied territories)\nEastern Ukraine:\xa0(Eastern Kharkiv Oblast-Western Luhansk Oblast)\nRussian sources claimed that Ukrainian troops continued counteroffensive actions along the Svatove-Kreminna line on November 5. Russian sources, including the Russian Ministry of Defense (MoD), reported that Ukrainian troops conducted an assault in the direction of Kuzemivka, 13km northwest of Svatove.\xa0A Russian milblogger claimed that Ukrainian troops crossed the Zherebets River west of Svatove and are probing Russian positions along the Kuzemivka-Kolomyichykha line.\xa0Geolocated footage shows Ukrainian troops conducting strikes on Russian armored vehicles about 30km northwest of Svatove, indicating that Russian troops maintain positions in the Yahidne-Orlianka area.\xa0A Russian milblogger claimed that Ukrainian forces re regrouping in this area after a failed assault on Yahidne.\xa0A Russian milblogger reported that Ukrainian troops continued attempted attacks towards Kreminna.\xa0The Ukrainian General Staff reported that Ukrainian troops repelled a Russian attack on Bilohorivka, 10km south of Kreminna.\xa0Russian sources also claimed that Ukrainian forces conducted a HIMARS strike on Russian positions in Svatove and Kreminna and shelled Russian positions along the Svatove-Kreminna line.\xa0\n\nSouthern Ukraine:\xa0(Kherson Oblast)\nRussian forces continued to set up defensive positions along the Dnipro River on November 5. Spokesperson for the Ukrainian Southern Forces, Nataliya Humenyuk, stated that Russian forces are building strong defensive positions on the left (eastern) bank of the Dnipro River with firing positions that they will use to target Ukrainian forces on the right (western) bank.\xa0Humenyuk added that Russian forces are still operating on the right bank. Ukraine’s Southern Operational Command noted that Russian forces are still conducting maneuvers and setting up defensive lines on the right bank, while simultaneously mining the left bank and evacuating civilians at least 15km away from the coast.\xa0The Ukrainian Resistance Center specified that Russian forces are preparing Nova Kakhovka (on the left bank) for battle by mining underground communications lines such as sewers.\xa0Ukraine’s Southern Operational Command also reiterated that Russian forces are continuing to destroy civilian watercraft and have already destroyed over 50 vessels.\xa0ISW has previously assessed that Russian forces are likely attempting to prevent Ukrainian forces from chasing them to the left bank following a fighting withdrawal.\n\nUkrainian and Russian sources did not report significant changes in the situation on the frontlines on November 5. The Ukrainian General Staff reported that Russian forces continued to shell Ukrainian positions northwest of Kherson City, in southeastern Mykolaiv Oblast, and near the Inhulets River.\xa0Ukraine’s Southern Operational Command added that Russian forces used S-300 anti-aircraft missiles to target ground targets in Beryslav Raion.\xa0The Russian Ministry of Defense (MoD) claimed that Russian forces repelled Ukrainian attacks in the directions of Sablukivka and Sukhanove, about 40km and 34km northeast of Beryslav.\xa0Russian milbloggers and a Kherson City occupation deputy noted the lack of Ukrainian or Russian ground maneuvers.\xa0A Russian milblogger added that Russian forces are shelling Ukrainian forces along the E58 highway northwest of Kherson City, likely to disrupt Ukrainian attacks.\nUkrainian forces continued their interdiction campaign on November 5, targeting Russian logistics and transportation routes in Kherson Oblast. Ukrainian military officials reported that Ukrainian forces struck a Russian river crossing near Antonivsky Bridge, destroying a tugboat and damaging two other vessels.\xa0Ukrainian forces also reportedly struck a Russian military convoy awaiting to cross the Dnipro River in Olhivka, about 13km northwest of Nova Kakhovka.\xa0Ukrainian military officials added that Ukrainian forces shot down two Russian attack helicopters in Beryslav Raion, damaged Russian area of manpower accumulation in Radensk, and destroyed three ammunition depots in Beryslav and Kherson raions.\xa0Local Ukrainian sources reported witnessing explosions in Kherson City, and Russian sources accused Ukrainian forces of targeting evacuees.\xa0Local residents also reported a Ukrainian strike on Nibulon factory in Hola Prystan, about 14km southwest of Kherson City.\nRussian Main Effort—Eastern Ukraine\nRussian Subordinate Main Effort—Donetsk Oblast\xa0(Russian objective: Capture the entirety of Donetsk Oblast, the claimed territory of Russia’s proxies in Donbas)\nRussian forces continued offensive operations around Bakhmut on November 5. The Ukrainian General Staff reported that Ukrainian forces repelled assaults near Bakhmut; within a 30km radius northeast of Bakhmut near Spirne and Bakhmutske; and within a 20km radius south of Bakhmut near Ivanhrad, Klishchiivka, Ozarianivka, and Mayorsk.\xa0The Donetsk People’s Republic (DNR) head Denis Pushilin stated on November 4 that Russian forces made advances near Mayorsk and expressed hope that Russian forces would soon capture the settlement.\xa0A Russian milblogger claimed that Russian forces also conducted an assault northeast of Bakhmut near Verkhnokamianske.\xa0Another Russian milblogger claimed on November 5 that Ukrainian forces must constantly rotate units south of Bakhmut in the direction of Ivanhrad and Vesela Dolnya to respond to Wagner PMC units conducting offensives in the direction of\xa0\xa0Opytne.\xa0A separate Russian milblogger claimed on November 5 that Russian forces conducted an assault on Opytne with the aim of cutting off a section of the E50 highway.\xa0A different Russian milblogger claimed that Russian forces repelled Ukrainian counterattacks south of Bakhmut near Opytne and Kurdiumivka.\xa0The milblogger also claimed that Ukrainian forces are continuing to constrain the actions of Russian forces south of Bakhmut near Ivanhrad, Odradivka, Vesela Dolyna, and Zaitseve, and are preparing for urban battles in Bakhmut itself.\n\nRussian forces continued offensive operations in the Avdiivka-Donetsk City area on November 5. The Ukrainian General Staff reported that Ukrainian forces repelled Russian ground assaults near Kamianka and within a 35km radius southwest of Avdiivka near Pervomaiske, Nevelske, Marinka, and Novomykhailivka.\xa0A Russian milblogger claimed on November 5 that Russian forces also attempted to advance southwest of Avdiivka to Kostantinivka.\xa0Geolocated footage posted on November 5 shows that Russian forces are likely operating southwest of Avdiivka near Krasnohorivka.\xa0A BARS-13 (combat army reserve) source claimed that Russian and Ukrainian positions near Avdiivka are only 30 to 40 meters apart.\nRussia forces continued offensive operations in western Donetsk Oblast on November 5. The Ukrainian General Staff reported that Ukrainian forces repelled a Russian assault on Pavlivka (52km southwest of Donetsk City).\xa0Geolocated footage shows Ukrainian forces still control Pavlivka as of November 4.\xa0A Russian milblogger claimed that Pavlivka is of great tactical importance because there is a road interchange in the settlement and the surrounding rear areas are rocky terrain that makes vehicle maneuvers more difficult.\xa0The Ukrainian General Staff reported on November 5 that Russian forces continued routine indirect fire along the line of contact in Donetsk Oblast.\nSupporting Effort—Southern Axis\xa0(Russian objective: Maintain frontline positions and secure rear areas against Ukrainian strikes)\nRussian forces continued routine air, missile, and artillery strikes west of Hulyaipole, and in Dnipropetrovsk and Mykolaiv oblasts on November 5.\xa0Ukrainian sources reported that Russian forces struck Nikopol, Dnipropetrovsk Oblast and Vilniansk, Zaporizhia Oblast.\xa0Ukraine’s Southern Operational Command reported that Russian forces conducted drone attacks in Mykolaiv and Vinnytsia oblasts.\xa0Ukraine’s Southern Operational Command reported that Ukrainian air defenses shot down six Shahed-136 drones in Mykolaiv Oblast and two in Vinnytsia Oblast.\n\nMobilization and Force Generation Efforts\xa0(Russian objective: Expand combat power without conducting general mobilization)\nContinued poor conditions for mobilized soldiers are catalyzing general unrest and a large-scale protest at a mobilization collection point in Kazan on November 4. One social media user posted that almost 2,000 soldiers participated in the protest, though ISW cannot independently confirm the size of the crowd.\xa0Video posted by news agencies and to social media shows mobilized forces threatening violence and cha

In [21]:
data.head(5)

,id,date,short_url,title,text_title,full_url,html_content,html_content_v2,html_content_v3,html_content_v4
1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...
1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...
181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...
197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...
1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...

In [22]:
data['html_content_v5'] = data['html_content_v4'].apply(lambda x: re.sub(r'http(\S+.*\s)',"",x))
data['html_content_v6'] = data['html_content_v5'].apply(lambda x: re.sub(r'2022|2023|©2022|©2023|\xa0|\n',"",x))

In [23]:
data['html_content_v6'][0]

"Russian Offensive Campaign Assessment, November 5,  | ISW Options\t\t\t\tDOWNLOAD PAGE\t\t\t  PRINT PAGEShareSkip to contentSkip to Content   Donate Menu  Menu About ISWAbout ISWOur CapabilitiesISW’s Comparative AdvantageOur HistoryImproving the National Security DebateWho We AreMeet the TeamCareersJoin the MissionOpen PositionsMAP ROOMISW produces the world’s premier open-source conflict maps  SEE MAPSAnalysisAnalysisThe General Jack Keane Center for National SecurityMap RoomDive into ISW's Complete Map CatalogBriefing RoomVideos, Podcasts, and Interactive ContentResearch LibraryBrowse ISW's Entire Body of WorkTEAMS/PORTFOLIOSRussia & UkraineMiddle EastChina & TaiwanDefense of EuropeAdversary EntenteContemporary & Future WarGeospatial IntelligenceCognitive WarfareEducationEducationThe General David H. Petraeus Center for Emerging LeadersHertog War StudiesISW’s Premier Educational Program for UndergraduatesFellowshipsEnrichment and Advancement Opportunities for Entry-Level and Mid-Career ProfessionalsInternshipsLaunch your Career at ISW with an Internship in Open-Source Intelligence, Geospatial Intelligence, Cognitive Warfare, or CommunicationsResearch LibraryBrowse ISW’s published work, curated for maximum searchability  view insightsGet InvolvedGet InvolvedJoin the ISW Community and Help Us Safeguard America’s SecurityDonateYour Donations Keep ISW Independent, Nonpartisan, and ObjectivePlanned GivingSecure Your Legacy and Strengthen Future GenerationsOur PartnersPartnering With ISW Makes a Direct Impact on America’s Security and Future LeadersNewsroom Donate Russia & UkraineUkraineRussian Offensive Campaign AssessmentRussian Offensive Campaign Assessment, November 5, November 6, Jump toPreviousNextRussian Offensive Campaign Assessment, November 5, Karolina Hird, Kateryna Stepanenko, Riley Bailey, Angela Howard, and Mason ClarkNovember 5, 6:30 pm ETClickhereto see ISW’s interactive map of the Russian invasion of Ukraine. This map is updated daily alongside the static maps present in this report.Wagner Group financier Yevgeny Prigozhin seeks to obfuscate his efforts to strengthen his independent power base with an appeal to the concept of Russia’s historic unity.Prigozhin provided a vague response to a media inquiry regarding his recent visit to Kursk Oblast on Russia’s Unity Day (November 4), during which he had indirectly implied that Wagner forces are involved in upholding Russia’s unity.Prigozhin stated that Russian people, businesses, government, and army need to come together to fight for Russia’s sovereignty and its great future while deflecting from the journalist’s question regarding Prigozhin’s reported meeting with Kursk businessmen about the organization of an unspecified people’s militia – outside of formal Russian military command structures. Prigozhin also noted that Russia has all the ingredients to achieve its goals including a strong president, cohesive army, and great nationhood, which he concluded with an out-of-place greeting from Wagner fighters. Prigozhin later claimed in a follow up media response that his “independence” does not contradict Russian President Vladimir Putin’s politics as some audiences have interpreted.Prigozhin’s rather sarcastic statements have several underlying implications for his perception of his power within Russia. ISW previously reported that Kursk Oblast officials announced the construction of second and third lines of defenses in the region, and if Prigozhin’s meeting with local businessmen took place, may indicate that he is attempting to expand his influence in the region.Prigozhin’s comment on Russia’s “cohesive army” next to Putin was likely thinly-veiled sarcasm, given that Prigozhin has repeatedly criticized the Russian Armed Forces on numerous occasions.Prigozhin also directly recognized that he is an independent entity, which as ISW previously assessed, relieves him of some obligations to the Kremlin and the Russian Ministry of Defense (MoD).Putin’s dependency on Prigozhin’s forces around Bakhmut also allows Prigozhin privileges such as voicing his criticisms of the Kremlin or the Russian Armed Forces without significant ramifications. Prigozhin has also coincidentally opened his Wagner Center in St. Petersburg on Russia’s Unity Day.However, Prigozhin is notably shielding his efforts to build an independent power base and shape the conduct of Russia’s invasion of Ukraine with language focused on Russian Unity – likely both to appeal to Russian nationalists and civilians and to deflect criticism of his fairly overt efforts to build an independent power base.Prigozhin continues to rely on ineffective convicts to staff his forces.Prigozhin declined to comment on a reporter’s question regarding ongoing recruitment drives at Krasnoyarsk Krai penal colonies, despite previously openly discussing prisoner participation in the war with Russian outlets likeRiaFan.Russian opposition outletThe Insider,however, found that over 500 prisoners recruited into Wagner units have died in the past two months.The publication added that Wagner lost between 800 and 1,000 mercenaries in Ukraine, indicating convicts comprise a large proportion of Wagner’s forces in Ukraine. Ukrainian intelligence officials also previously reported that many prisoners suffering from infectious diseases infected Wagner troops, to which Prigozhin responded that he does not discriminate on the basis of illness.Iranian Foreign Minister Hossein Amir-Abdollahian confirmed that Iran sent Russia combat drones.Amir-Abdollahian stated on November 5 that Iran “gave a limited number of drones to Russia months before” the war in Ukraine.Amir-Abdollahian also claimed that if Ukrainian officials could prove that the Russian military has used Iranian-made drones in Ukraine then Iranian officials would “not be indifferent” to the concern – falsely and ridiculously implying that Russia has not used the drones that he admitted Iran has provided.Iran’s confirmation of the drone shipments further supports ISW’s previous assessments that Russia is sourcing Iranian-made weapons systems to address the depletion of its high-precision munitions arsenal.ISW previously assessed that Iran is likely already exploiting Russian reliance on these Iranian-made weapons systems to request Russian assistance with its nuclear program.The nuclear assistance requests and the recognition of the drone shipments are both indicators that Iranian officials may intend to more clearly establish an explicit bilateral security relationship with Russia in which they are more equal partners.Former Donetsk People’s Republic (DNR) Security Minister and current DNR military commander Aleksandr Khodakovsky claimed on November 5 that Russian friendly fire may have caused up to 60% of total Russian losses since the end of Russian offensive operations in Mariupol in mid-May.Even if this statistic is exaggerated, the fact that a Russian commander is publicly speculating on such a damning indicator of Russian and proxy competency indicates the deep challenges Russian forces face. Friendly fire typically does account for a limited number of losses in war but ordinarily nowhere near 60% of total casualties, which demonstrates a lack of communication and command and control coordination between Russian forces. Russian and Ukrainian sources also reported that a Russian rotation returning to its base near Pavlivka, Donetsk Oblast on November 5 drove into a ditch constructed by army subcontractors without prior discussion or warning, further demonstrating a widespread lack of cross-training and coordination between Russian troops.The frequent replacement of Russian military leaders, promotion of inexperienced soldiers, and cobbled-together Russian force composition including Russian contract soldiers, Russian mobilized soldiers, DNR and Luhansk People’s Republic (LNR) forces, and Wagner Group forces exacerbate the fragmented nature of the Russian chain of command and ineffectiveness of Russian forces and likely contributes to frequent friendly fire incidents.Key TakeawaysWagner Group financier Yevheniy Prigozhin seeks to obfuscate his efforts to strengthen his independent power base with an appeal to the concept of Russia’s historic unity.Iranian Foreign Minister Hossein Amir-Abdollahian confirmed that Iran began providing Russia drones before February 24, but strangely denied that Russian forces have used them in combat.DNR military commander Aleksandr Khodakovsky claimed that Russian friendly fire may have caused up to 60% of total Russian losses since mid-May.Ukrainian troops reportedly continued counteroffensives along the Svatove-Kreminna line.Russian forces continued to set up defensive positions along the Dnipro River.Ukrainian forces continued to target Russian logistics and transportation in Kherson Oblast.Russian forces continued to attack around Bakhmut and claimed unspecified advances.Russian forces continued unsuccessful offensive operations in the Avdiivka-Donetsk City area and in western Donetsk.Continued poor conditions for mobilized soldiers catalyzed a large-scale protest in Kazan.Unknown actors reportedly attempted to assassinate high-profile Donetsk People’s Republic (DNR) Supreme Court Judge Aleksandr Nikulin.Russia continues to deploy personnel to staff administrative positions in occupied areas.Russian forces continued forced evacuations in Kherson Oblast. Over 80% of Kherson residents reportedly have evacuated.We do not report in detail on Russian war crimes because those activities are well-covered in Western media and do not directly affect the military operations we are assessing and forecasting. We will continue to evaluate and report on the effects of these criminal activities on the Ukrainian military and population and specifically on combat in Ukrainian urban areas. We utterly condemn these Russian violations of the laws of armed conflict, Geneva Conventions, and humanity even though we do not describe them in these reports.Ukrainian Counteroffensives—Southern and Eastern UkraineRussian Main Effort—Eastern Ukraine (comprised of one subordinate and two supporting efforts);Russian Subordinate Main Effort—Capture the entirety of Donetsk OblastRussian Supporting Effort—Southern AxisRussian Mobilization and Force Generation EffortsActivities in Russian-occupied AreasUkrainian Counteroffensives(Ukrainian efforts to liberate Russian-occupied territories)Eastern Ukraine:(Eastern Kharkiv Oblast-Western Luhansk Oblast)Russian sources claimed that Ukrainian troops continued counteroffensive actions along the Svatove-Kreminna line on November 5. Russian sources, including the Russian Ministry of Defense (MoD), reported that Ukrainian troops conducted an assault in the direction of Kuzemivka, 13km northwest of Svatove.A Russian milblogger claimed that Ukrainian troops crossed the Zherebets River west of Svatove and are probing Russian positions along the Kuzemivka-Kolomyichykha line.Geolocated footage shows Ukrainian troops conducting strikes on Russian armored vehicles about 30km northwest of Svatove, indicating that Russian troops maintain positions in the Yahidne-Orlianka area.A Russian milblogger claimed that Ukrainian forces re regrouping in this area after a failed assault on Yahidne.A Russian milblogger reported that Ukrainian troops continued attempted attacks towards Kreminna.The Ukrainian General Staff reported that Ukrainian troops repelled a Russian attack on Bilohorivka, 10km south of Kreminna.Russian sources also claimed that Ukrainian forces conducted a HIMARS strike on Russian positions in Svatove and Kreminna and shelled Russian positions along the Svatove-Kreminna line.Southern Ukraine:(Kherson Oblast)Russian forces continued to set up defensive positions along the Dnipro River on November 5. Spokesperson for the Ukrainian Southern Forces, Nataliya Humenyuk, stated that Russian forces are building strong defensive positions on the left (eastern) bank of the Dnipro River with firing positions that they will use to target Ukrainian forces on the right (western) bank.Humenyuk added that Russian forces are still operating on the right bank. Ukraine’s Southern Operational Command noted that Russian forces are still conducting maneuvers and setting up defensive lines on the right bank, while simultaneously mining the left bank and evacuating civilians at least 15km away from the coast.The Ukrainian Resistance Center specified that Russian forces are preparing Nova Kakhovka (on the left bank) for battle by mining underground communications lines such as sewers.Ukraine’s Southern Operational Command also reiterated that Russian forces are continuing to destroy civilian watercraft and have already destroyed over 50 vessels.ISW has previously assessed that Russian forces are likely attempting to prevent Ukrainian forces from chasing them to the left bank following a fighting withdrawal.Ukrainian and Russian sources did not report significant changes in the situation on the frontlines on November 5. The Ukrainian General Staff reported that Russian forces continued to shell Ukrainian positions northwest of Kherson City, in southeastern Mykolaiv Oblast, and near the Inhulets River.Ukraine’s Southern Operational Command added that Russian forces used S-300 anti-aircraft missiles to target ground targets in Beryslav Raion.The Russian Ministry of Defense (MoD) claimed that Russian forces repelled Ukrainian attacks in the directions of Sablukivka and Sukhanove, about 40km and 34km northeast of Beryslav.Russian milbloggers and a Kherson City occupation deputy noted the lack of Ukrainian or Russian ground maneuvers.A Russian milblogger added that Russian forces are shelling Ukrainian forces along the E58 highway northwest of Kherson City, likely to disrupt Ukrainian attacks.Ukrainian forces continued their interdiction campaign on November 5, targeting Russian logistics and transportation routes in Kherson Oblast. Ukrainian military officials reported that Ukrainian forces struck a Russian river crossing near Antonivsky Bridge, destroying a tugboat and damaging two other vessels.Ukrainian forces also reportedly struck a Russian military convoy awaiting to cross the Dnipro River in Olhivka, about 13km northwest of Nova Kakhovka.Ukrainian military officials added that Ukrainian forces shot down two Russian attack helicopters in Beryslav Raion, damaged Russian area of manpower accumulation in Radensk, and destroyed three ammunition depots in Beryslav and Kherson raions.Local Ukrainian sources reported witnessing explosions in Kherson City, and Russian sources accused Ukrainian forces of targeting evacuees.Local residents also reported a Ukrainian strike on Nibulon factory in Hola Prystan, about 14km southwest of Kherson City.Russian Main Effort—Eastern UkraineRussian Subordinate Main Effort—Donetsk Oblast(Russian objective: Capture the entirety of Donetsk Oblast, the claimed territory of Russia’s proxies in Donbas)Russian forces continued offensive operations around Bakhmut on November 5. The Ukrainian General Staff reported that Ukrainian forces repelled assaults near Bakhmut; within a 30km radius northeast of Bakhmut near Spirne and Bakhmutske; and within a 20km radius south of Bakhmut near Ivanhrad, Klishchiivka, Ozarianivka, and Mayorsk.The Donetsk People’s Republic (DNR) head Denis Pushilin stated on November 4 that Russian forces made advances near Mayorsk and expressed hope that Russian forces would soon capture the settlement.A Russian milblogger claimed that Russian forces also conducted an assault northeast of Bakhmut near Verkhnokamianske.Another Russian milblogger claimed on November 5 that Ukrainian forces must constantly rotate units south of Bakhmut in the direction of Ivanhrad and Vesela Dolnya to respond to Wagner PMC units conducting offensives in the direction ofOpytne.A separate Russian milblogger claimed on November 5 that Russian forces conducted an assault on Opytne with the aim of cutting off a section of the E50 highway.A different Russian milblogger claimed that Russian forces repelled Ukrainian counterattacks south of Bakhmut near Opytne and Kurdiumivka.The milblogger also claimed that Ukrainian forces are continuing to constrain the actions of Russian forces south of Bakhmut near Ivanhrad, Odradivka, Vesela Dolyna, and Zaitseve, and are preparing for urban battles in Bakhmut itself.Russian forces continued offensive operations in the Avdiivka-Donetsk City area on November 5. The Ukrainian General Staff reported that Ukrainian forces repelled Russian ground assaults near Kamianka and within a 35km radius southwest of Avdiivka near Pervomaiske, Nevelske, Marinka, and Novomykhailivka.A Russian milblogger claimed on November 5 that Russian forces also attempted to advance southwest of Avdiivka to Kostantinivka.Geolocated footage posted on November 5 shows that Russian forces are likely operating southwest of Avdiivka near Krasnohorivka.A BARS-13 (combat army reserve) source claimed that Russian and Ukrainian positions near Avdiivka are only 30 to 40 meters apart.Russia forces continued offensive operations in western Donetsk Oblast on November 5. The Ukrainian General Staff reported that Ukrainian forces repelled a Russian assault on Pavlivka (52km southwest of Donetsk City).Geolocated footage shows Ukrainian forces still control Pavlivka as of November 4.A Russian milblogger claimed that Pavlivka is of great tactical importance because there is a road interchange in the settlement and the surrounding rear areas are rocky terrain that makes vehicle maneuvers more difficult.The Ukrainian General Staff reported on November 5 that Russian forces continued routine indirect fire along the line of contact in Donetsk Oblast.Supporting Effort—Southern Axis(Russian objective: Maintain frontline positions and secure rear areas against Ukrainian strikes)Russian forces continued routine air, missile, and artillery strikes west of Hulyaipole, and in Dnipropetrovsk and Mykolaiv oblasts on November 5.Ukrainian sources reported that Russian forces struck Nikopol, Dnipropetrovsk Oblast and Vilniansk, Zaporizhia Oblast.Ukraine’s Southern Operational Command reported that Russian forces conducted drone attacks in Mykolaiv and Vinnytsia oblasts.Ukraine’s Southern Operational Command reported that Ukrainian air defenses shot down six Shahed-136 drones in Mykolaiv Oblast and two in Vinnytsia Oblast.Mobilization and Force Generation Efforts(Russian objective: Expand combat power without conducting general mobilization)Continued poor conditions for mobilized soldiers are catalyzing general unrest and a large-scale protest at a mobilization collection point in Kazan on November 4. One social media user posted that almost 2,000 soldiers participated in the protest, though ISW cannot independently confirm the size of the crowd.Video posted by news agencies and to social media shows mobilized forces threatening violence and chanting slurs at a reported colonel after demanding that he explain the lack of provision of basic necessities including food, water, and heat.A Tatarstan government news agency published an article on November 5 claiming authorities had resolved the relevant issues.However, Russian authorities are highly unlikely to be able to fix such issues and halt the resulting protests in the near future. Russian and Ukrainian sources provided continued reports of a lack of medical care, shelter, heating, and equipment for mobilized soldiers on November 4 and 5.ISW has reported on a series of protests due to under-provisioning for Russian mobilized soldiers.Russian forces face additional challenges generating combat power due to pervasive official ineptitude and possible domestic sabotage efforts. One Russian milblogger accused inert mid- and high-level government officials, military leaders, and ministerial deputies of criminal sabotage of mobilization efforts due to incompetence on November 5.Video posted to Twitter on November 4 shows R

In [24]:
data.head()

,id,date,short_url,title,text_title,full_url,html_content,html_content_v2,html_content_v3,html_content_v4,html_content_v5,html_content_v6
1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,"Russian Offensive Campaign Assessment, Februar..."
1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,"Russian Offensive Campaign Assessment, Februar..."
181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,"Russian Offensive Campaign Assessment, Februar..."
197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,"Russian Offensive Campaign Assessment, Februar..."
1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...",\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,\n\n\n\n\n\n\nRussian Offensive Campaign Asses...,"Russian Offensive Campaign Assessment, Februar..."

In [25]:
data2 = data.drop(['html_content_v2','html_content_v3','html_content_v4','html_content_v5'],axis=1)

In [26]:
data2.head()

,id,date,short_url,title,text_title,full_url,html_content,html_content_v6
1201,1202,2022-02-24,2022_02_24,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
1366,1367,2022-02-25,2022_02_25,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
181,182,2022-02-26,2022_02_26,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
197,198,2022-02-27,2022_02_27,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."
1106,1107,2022-02-28,2022_02_28,"Russian Offensive Campaign Assessment, Februar...","Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"<!DOCTYPE html>\n<html lang=""en-US"">\n<head>\n...","Russian Offensive Campaign Assessment, Februar..."

In [27]:
#data2.to_csv('all_isw_reports_full.csv')