In [42]:
import pandas as pd
from datetime import datetime

In [43]:
path = "<your path for parsed dataset>"

In [44]:
data = pd.read_csv(path)

In [45]:
data.head(5)

,title,date,text
0,"Russian Offensive Campaign Assessment, Novembe...","November 5, 2022","Karolina Hird, Kateryna Stepanenko, Riley Bail..."
1,"Russian Offensive Campaign Assessment, August ...","August 14, 2022","Kateryna Stepanenko, Karolina Hird, Grace Mapp..."
2,Russian Offensive Campaign Assessment: January...,"January 5, 2024","Russian Offensive Campaign Assessment, January..."
3,"Russian Offensive Campaign Assessment, Septemb...","September 21, 2022","Karolina Hird, Kateryna Stepanenko, Grace Mapp..."
4,"Russian Offensive Campaign Assessment, October...","October 30, 2022","Frederick W. Kagan October 30, 5:00 pm ET ISW ..."

In [46]:
data.tail(7)

,title,date,text
1457,"Russian Offensive Campaign Assessment, January...","January 21, 2025","Russian Offensive Campaign Assessment, January..."
1458,"Russian Offensive Campaign Assessment, April 1...","April 13, 2022","Mason Clark, Kateryna Stepanenko, and Karolina..."
1459,"Russian Offensive Campaign Assessment, Novembe...","November 21, 2022","Karolina Hird, Grace Mappes, Riley Bailey, Lay..."
1460,"Russian Offensive Campaign Assessment, October...","October 14, 2022","Karolina Hird, Katherine Lawlor, Grace Mappes,..."
1461,"Russian Offensive Campaign Assessment, Decembe...","December 29, 2022","Angela Howard, Riley Bailey, Karolina Hird, Ge..."
1462,"Russian Offensive Campaign Assessment, May 26,...","May 26, 2022","Karolina Hird, Mason Clark, and George Barros ..."
1463,"Russian Offensive Campaign Assessment, Septemb...","September 5, 2022","Kateryna Stepanenko, Karolina Hird, Angela How..."

In [47]:
data.shape

(1464, 3)

In [48]:
data.columns

Index(['title', 'date', 'text'], dtype='object')

In [49]:
data.columns = [ 'title', 'date', 'text']

print(data.head())

data.to_csv(path, index=False)

                                               title                date  \
0  Russian Offensive Campaign Assessment, Novembe...    November 5, 2022
1  Russian Offensive Campaign Assessment, August ...     August 14, 2022
2  Russian Offensive Campaign Assessment: January...     January 5, 2024
3  Russian Offensive Campaign Assessment, Septemb...  September 21, 2022
4  Russian Offensive Campaign Assessment, October...    October 30, 2022

                                                text
0  Karolina Hird, Kateryna Stepanenko, Riley Bail...
1  Kateryna Stepanenko, Karolina Hird, Grace Mapp...
2  Russian Offensive Campaign Assessment, January...
3  Karolina Hird, Kateryna Stepanenko, Grace Mapp...
4  Frederick W. Kagan October 30, 5:00 pm ET ISW ...

In [50]:
data.tail(5)

,title,date,text
1459,"Russian Offensive Campaign Assessment, Novembe...","November 21, 2022","Karolina Hird, Grace Mappes, Riley Bailey, Lay..."
1460,"Russian Offensive Campaign Assessment, October...","October 14, 2022","Karolina Hird, Katherine Lawlor, Grace Mappes,..."
1461,"Russian Offensive Campaign Assessment, Decembe...","December 29, 2022","Angela Howard, Riley Bailey, Karolina Hird, Ge..."
1462,"Russian Offensive Campaign Assessment, May 26,...","May 26, 2022","Karolina Hird, Mason Clark, and George Barros ..."
1463,"Russian Offensive Campaign Assessment, Septemb...","September 5, 2022","Kateryna Stepanenko, Karolina Hird, Angela How..."

In [51]:
def convert_date(date_str):
    try:
        clean_date = date_str.split(" - ")[0].strip()
        return datetime.strptime(clean_date, "%Y %d, %m").strftime("%Y-%m-%d")
    except Exception as e:
        print(f"Error parsing date: {date_str} - {e}")
        return None 

print("Унікальні значення перед обробкою:\n", data["date"].unique())

data["date"] = data["date"].astype(str).apply(convert_date)

print("Унікальні значення після обробки:\n", data["date"].unique())

Унікальні значення перед обробкою:
 ['November 5, 2022' 'August 14, 2022' 'January 5, 2024'
 'September 21, 2022' 'October 30, 2022' 'May 2, 2022' 'July 27, 2022'
 'October 28, 2022' 'December 15, 2022' 'February 15, 2025'
 'March 20, 2022' 'June 12, 2022' 'October 23, 2022' 'May 11, 2022'
 'April 24, 2022' 'June 19, 2022' 'November 16, 2022' 'August 7, 2022'
 'June 1, 2022' 'May 9, 2022' 'December 6, 2022' 'May 7, 2022'
 'December 8, 2022' 'September 24, 2022' 'February 8, 2025'
 'August 11, 2022' 'June 17, 2022' 'November 18, 2022' 'August 9, 2022'
 'January 18, 2025' 'March 25, 2022' 'December 10, 2022' 'July 22, 2022'
 'January 13, 2025' 'August 2, 2022' 'January 28, 2025'
 'November 13, 2022' 'April 21, 2022' 'Unknown' 'July 29, 2022'
 'October 26, 2022' 'February 3, 2025' 'December 3, 2022' 'July 31, 2022'
 'June 4, 2022' 'March 11, 2022' 'February 24, 2025' 'September 8, 2022'
 'October 19, 2022' 'December 24, 2022' 'July 16, 2022' 'October 1, 2022'
 'September 10, 2022' 'March 9, 2022' 'August 25, 2022' 'April 6, 2022'
 'July 5, 2022' 'June 30, 2022' 'January 4, 2025' 'March 2, 2022'
 'January 27, 2025' 'November 27, 2022' 'April 15, 2022' 'June 28, 2022'
 'May 20, 2022' 'October 12, 2022' 'September 3, 2022' 'February 14, 2025'
 'July 13, 2022' 'December 21, 2022' 'February 21, 2025'
 'January 29, 2025' 'March 14, 2022' 'January 12, 2025'
 'November 29, 2022' 'June 26, 2022' 'April 3, 2022' 'August 20, 2022'
 'January 31, 2025' 'September 15, 2022' 'February 2, 2025'
 'October 4, 2022' 'March 7, 2022' 'April 8, 2022' 'September 6, 2022'
 'October 17, 2022' 'May 25, 2022' 'July 18, 2022' 'April 10, 2022'
 'November 22, 2022' 'January 22, 2025' 'February 19, 2025'
 'February 22, 2025' 'December 19, 2022' 'October 24, 2022' 'May 16, 2022'
 'April 23, 2022' 'November 11, 2022' 'January 11, 2025' 'January 9, 2025'
 'August 18, 2022' 'November 9, 2022' 'June 6, 2022' 'December 1, 2022'
 'February 1, 2025' 'April 30, 2022' 'November 2, 2022' 'August 13, 2022'
 'January 2, 2023' 'September 26, 2022' 'May 5, 2025' 'July 20, 2022'
 'December 12, 2022' 'February 12, 2025' 'March 27, 2022' 'June 15, 2022'
 'April 28, 2022' 'January 14, 2025' 'August 5, 2022' 'November 14, 2022'
 'April 26, 2022' 'May 13, 2022' 'October 21, 2022' 'September 30, 2022'
 'February 4, 2025' 'September 28, 2022' 'December 4, 2022' 'June 3, 2022'
 'March 31, 2022' 'September 23, 2022' 'January 7, 2025' 'August 16, 2022'
 'November 7, 2022' 'June 8, 2022' 'June 10, 2022' 'January 24, 2025'
 'March 22, 2022' 'February 17, 2025' 'December 17, 2022' 'July 25, 2022'
 'May 18, 2022' 'December 30, 2022' 'July 2, 2022' 'August 29, 2022'
 'March 5, 2022' 'August 31, 2022' 'November 20, 2022' 'April 12, 2022'
 'May 27, 2022' 'December 28, 2022' 'October 15, 2022' 'September 4, 2022'
 'February 28, 2025' 'June 24, 2022' 'April 19, 2022' 'February 23, 2025'
 'February 18, 2025' 'December 23, 2022' 'July 11, 2025' 'July 9, 2022'
 'October 6, 2022' 'September 17, 2022' 'January 8, 2025'
 'August 22, 2022' 'July 7, 2022' 'October 8, 2022' 'September 19, 2022'
 'September 1, 2022' 'October 10, 2022' 'May 22, 2022' 'April 17, 2022'
 'November 25, 2022' 'January 25, 2025' 'July 14, 2022' 'May 29, 2022'
 'December 26, 2022' 'February 26, 2025' 'March 13, 2022' 'June 21, 2022'
 'April 4, 2022' 'August 27, 2022' 'September 12, 2022' 'October 3, 2022'
 'May 31, 2022' 'April 5, 2022' 'August 26, 2022' 'September 13, 2022'
 'October 2, 2022' 'May 30, 2022' 'May 28, 2022' 'July 15, 2022'
 'December 27, 2022' 'February 27, 2025' 'March 12, 2022' 'June 20, 2022'
 'October 11, 2022' 'May 23, 2022' 'April 16, 2022' 'November 24, 2024'
 'March 19, 2022' 'March 1, 2022' 'July 6, 2022' 'October 9, 2022'
 'September 18, 2022' 'July 8, 2022' 'October 7, 2022'
 'September 16, 2022' 'August 23, 2022' 'April 18, 2022' 'June 25, 2022'
 'March 17, 2022' 'December 22, 2022' 'July 10, 2022' 'August 30, 2022'
 'November 21, 2022' 'April 13, 2022' 'May 26, 2022' 'October 14, 2022'
 'December 29, 2022' 'September 5, 2022' 'February 29, 2024'
 'December 31, 2022' 'July 3, 2022' 'August 28, 2022' 'March 4, 2022'
 'June 11, 2022' 'March 23, 2022' 'February 16, 2025' 'December 16, 2022'
 'May 19, 2022' 'July 24, 2022' 'May 1, 2022' 'September 22, 2022'
 'January 6, 2025' 'August 17, 2022' 'November 6, 2022' 'June 9, 2022'
 'February 5, 2025' 'September 29, 2022' 'December 5, 2022' 'June 2, 2022'
 'March 30, 2022' 'January 15, 2025' 'March 28, 2022' 'August 4, 2022'
 'November 15, 2022' 'April 27, 2022' 'May 12, 2022' 'October 20, 2022'
 'July 21, 2022' 'December 13, 2022' 'February 13, 2025' 'March 26, 2022'
 'April 29, 2022' 'June 14, 2022' 'November 3, 2022' 'August 12, 2025'
 'January 3, 2025' 'September 27, 2022' 'May 4, 2022' 'August 19, 2022'
 'November 8, 2022' 'June 7, 2022' 'October 25, 2022' 'December 18, 2022'
 'May 17, 2022' 'April 22, 2022' 'November 10, 2022' 'August 1, 2022'
 'January 10, 2025' 'September 7, 2022' 'October 16, 2022' 'July 19, 2022'
 'May 24, 2022' 'November 23, 2022' 'January 23, 2025' 'March 6, 2022'
 'April 9, 2022' 'July 1, 2022' 'April 2, 2022' 'November 30, 2022'
 'August 21, 2022' 'January 30, 2025' 'September 14, 2022'
 'October 5, 2022' 'July 12, 2022' 'December 20, 2022' 'February 20, 2025'
 'March 15, 2022' 'November 28, 2022' 'June 27, 2022' 'January 26, 2025'
 'November 26, 2022' 'June 29, 2022' 'April 14, 2022' 'May 21, 2022'
 'October 13, 2022' 'September 2, 2022' 'July 4, 2022' 'March 3, 2022'
 'September 11, 2022' 'March 8, 2022' 'August 24, 2022' 'April 7, 2023'
 'June 22, 2022' 'March 10, 2022' 'February 25, 2025' 'September 9, 2022'
 'October 18, 2022' 'July 17, 2022' 'December 2, 2022' 'July 30, 2022'
 'June 5, 2022' 'August 3, 2022' 'November 12, 2022' 'April 20, 2022'
 'July 28, 2022' 'May 15, 2022' 'October 27, 2022' 'November 19, 2022'
 'August 8, 2022' 'March 24, 2022' 'January 19, 2025' 'December 11, 2022'
 'July 23, 2022' 'May 6, 2022' 'December 9, 2022' 'September 25, 2022'
 'February 9, 2025' 'August 10, 2022' 'November 1, 2022' 'May 8, 2022'
 'December 7, 2022' 'October 22, 2022' 'May 10, 2022' 'June 18, 2022'
 'April 25, 2022' 'November 17, 2022' 'August 6, 2022' 'July 26, 2022'
 'December 14, 2022' 'October 29, 2022' 'March 21, 2022' 'June 13, 2022'
 'November 4, 2022' 'August 15, 2022' 'September 20, 2022'
 'October 31, 2022' 'May 3, 2022' 'January 17, 2025' 'February 7, 2025'
 'February 11, 2025' 'January 21, 2025' 'January 20, 2025'
 'February 10, 2025' 'February 6, 2025' 'January 16, 2025']
Error parsing date: November 5, 2022 - time data 'November 5, 2022' does not match format '%Y %d, %m'
Error parsing date: August 14, 2022 - time data 'August 14, 2022' does not match format '%Y %d, %m'
Error parsing date: January 5, 2024 - time data 'January 5, 2024' does not match format '%Y %d, %m'
Error parsing date: September 21, 2022 - time data 'September 21, 2022' does not match format '%Y %d, %m'
Error parsing date: October 30, 2022 - time data 'October 30, 2022' does not match format '%Y %d, %m'
Error parsing date: May 2, 2022 - time data 'May 2, 2022' does not match format '%Y %d, %m'
Error parsing date: July 27, 2022 - time data 'July 27, 2022' does not match format '%Y %d, %m'
Error parsing date: October 28, 2022 - time data 'October 28, 2022' does not match format '%Y %d, %m'
Error parsing date: December 15, 2022 - time data 'December 15, 2022' does not match format '%Y %d, %m'
Error parsing date: February 15, 2025 - time data 'February 15, 2025' does not match format '%Y %d, %m'
Error parsing date: March 20, 2022 - time data 'March 20, 2022' does not match format '%Y %d, %m'
Error parsing date: June 12, 2022 - time data 'June 12, 2022' does not match format '%Y %d, %m'
Error parsing date: October 23, 2022 - time data 'October 23, 2022' does not match format '%Y %d, %m'
Error parsing date: May 11, 2022 - time data 'May 11, 2022' does not match format '%Y %d, %m'
Error parsing date: April 24, 2022 - time data 'April 24, 2022' does not match format '%Y %d, %m'
Error parsing date: June 19, 2022 - time data 'June 19, 2022' does not match format '%Y %d, %m'
Error parsing date: November 16, 2022 - time data 'November 16, 2022' does not match format '%Y %d, %m'
Error parsing date: August 7, 2022 - time data 'August 7, 2022' does not match format '%Y %d, %m'
Error parsing date: June 1, 2022 - time data 'June 1, 2022' does not match format '%Y %d, %m'
Error parsing date: May 9, 2022 - time data 'May 9, 2022' does not match format '%Y %d, %m'
Error parsing date: December 6, 2022 - time data 'December 6, 2022' does not match format '%Y %d, %m'
Error parsing date: May 7, 2022 - time data 'May 7, 2022' does not match format '%Y %d, %m'
Error parsing date: December 8, 2022 - time data 'December 8, 2022' does not match format '%Y %d, %m'
Error parsing date: September 24, 2022 - time data 'September 24, 2022' does not match format '%Y %d, %m'
Error parsing date: February 8, 2025 - time data 'February 8, 2025' does not match format '%Y %d, %m'
Error parsing date: August 11, 2022 - time data 'August 11, 2022' does not match format '%Y %d, %m'
Error parsing date: June 17, 2022 - time data 'June 17, 2022' does not match format '%Y %d, %m'
Error parsing date: November 18, 2022 - time data 'November 18, 2022' does not match format '%Y %d, %m'
Error parsing date: August 9, 2022 - time data 'August 9, 2022' does not match format '%Y %d, %m'
Error parsing date: January 18, 2025 - time data 'January 18, 2025' does not match format '%Y %d, %m'
Error parsing date: March 25, 2022 - time data 'March 25, 2022' does not match format '%Y %d, %m'
Error parsing date: December 10, 2022 - time data 'December 10, 2022' does not match format '%Y %d, %m'
Error parsing date: July 22, 2022 - time data 'July 22, 2022' does not match format '%Y %d, %m'
Error parsing date: January 13, 2025 - time data 'January 13, 2025' does not match format '%Y %d, %m'
Error parsing date: August 2, 2022 - time data 'August 2, 2022' does not match format '%Y %d, %m'
Error parsing date: January 28, 2025 - time data 'January 28, 2025' does not match format '%Y %d, %m'
Error parsing date: November 13, 2022 - time data 'November 13, 2022' does not match format '%Y %d, %m'
Error parsing date: April 21, 2022 - time data 'April 21, 2022' does not match format '%Y %d, %m'
Error parsing date: Unknown - time data 'Unknown' does not match format '%Y %d, %m'
Error parsing date: July 29, 2022 - time data 'July 29, 2022' does not match format '%Y %d, %m'
Error parsing date: October 26, 2022 - time data 'October 26, 2022' does not match format '%Y %d, %m'
Error parsing date: February 3, 2025 - time data 'February 3, 2025' does not match format '%Y %d, %m'
Error parsing date: December 3, 2022 - time data 'December 3, 2022' does not match format '%Y %d, %m'
Error parsing date: July 31, 2022 - time data 'July 31, 2022' does not match format '%Y %d, %m'
Error parsing date: June 4, 2022 - time data 'June 4, 2022' does not match format '%Y %d, %m'
Error parsing date: Unknown - time data 'Unknown' does not match format '%Y %d, %m'
Error parsing date: March 11, 2022 - time data 'March 11, 2022' does not match format '%Y %d, %m'
Error parsing date: February 24, 2025 - time data 'February 24, 2025' does not match format '%Y %d, %m'
Error parsing date: September 8, 2022 - time data 'September 8, 2022' does not match format '%Y %d, %m'
Error parsing date: October 19, 2022 - time data 'October 19, 2022' does not match format '%Y %d, %m'
Error parsing date: December 24, 2022 - time data 'December 24, 2022' does not match format '%Y %d, %m'
Error parsing date: July 16, 2022 - time data 'July 16, 2022' does not match format '%Y %d, %m'
Error parsing date: October 1, 2022 - time data 'October 1, 2022' does not match format '%Y %d, %m'
Error parsing date: September 10, 2022 - time data 'September 10, 2022' does not match format '%Y %d, %m'
Error parsing date: March 9, 2022 - time data 'March 9, 2022' does not match format '%Y %d, %m'
Error parsing date: August 25, 2022 - time data 'August 25, 2022' does not match format '%Y %d, %m'
Error parsing date: April 6, 2022 - time data 'April 6, 2022' does not match format '%Y %d, %m'
Error parsing date: July 5, 2022 - time data 'July 5, 2022' does not match format '%Y %d, %m'
Error parsing date: June 30, 2022 - time data 'June 30, 2022' does not match format '%Y %d, %m'
Error parsing date: January 4, 2025 - time data 'January 4, 2025' does not match format '%Y %d, %m'
Error parsing date: March 2, 2022 - time data 'March 2, 2022' does not match format '%Y %d, %m'
Error parsing date: January 27, 2025 - time data 'January 27, 2025' does not match format '%Y %d, %m'
Error parsing date: November 27, 2022 - time data 'November 27, 2022' does not match format '%Y %d, %m'
Error parsing date: April 15, 2022 - time data 'April 15, 2022' does not match format '%Y %d, %m'
Error parsing date: June 28, 2022 - time data 'June 28, 2022' does not match format '%Y %d, %m'
Error parsing date: May 20, 2022 - time data 'May 20, 2022' does not match format '%Y %d, %m'
Error parsing date: October 12, 2022 - time data 'October 12, 2022' does not match format '%Y %d, %m'
Error parsing date: September 3, 2022 - time data 'September 3, 2022' does not match format '%Y %d, %m'
Error parsing date: February 14, 2025 - time data 'February 14, 2025' does not match format '%Y %d, %m'
Error parsing date: July 13, 2022 - time data 'July 13, 2022' does not match format '%Y %d, %m'
Error parsing date: December 21, 2022 - time data 'December 21, 2022' does not match format '%Y %d, %m'
Error parsing date: February 21, 2025 - time data 'February 21, 2025' does not match format '%Y %d, %m'
Error parsing date: January 29, 2025 - time data 'January 29, 2025' does not match format '%Y %d, %m'
Error parsing date: March 14, 2022 - time data 'March 14, 2022' does not match format '%Y %d, %m'
Error parsing date: January 12, 2025 - time data 'January 12, 2025' does not match format '%Y %d, %m'
Error parsing date: November 29, 2022 - time data 'November 29, 2022' does not match format '%Y %d, %m'
Error parsing date: June 26, 2022 - time data 'June 26, 2022' does not match format '%Y %d, %m'
Error parsing date: April 3, 2022 - time data 'April 3, 2022' does not match format '%Y %d, %m'
Error parsing date: August 20, 2022 - time data 'August 20, 2022' does not match format '%Y %d, %m'
Error parsing date: January 31, 2025 - time data 'January 31, 2025' does not match format '%Y %d, %m'
Error parsing date: September 15, 2022 - time data 'September 15, 2022' does not match format '%Y %d, %m'
Error parsing date: February 2, 2025 - time data 'February 2, 2025' does not match format '%Y %d, %m'
Error parsing date: October 4, 2022 - time data 'October 4, 2022' does not match format '%Y %d, %m'
Error parsing date: March 7, 2022 - time data 'March 7, 2022' does not match format '%Y %d, %m'
Error parsing date: April 8, 2022 - time data 'April 8, 2022' does not match format '%Y %d, %m'
Error parsing date: September 6, 2022 - time data 'September 6, 2022' does not match format '%Y %d, %m'
Error parsing date: October 17, 2022 - time data 'October 17, 2022' does not match format '%Y %d, %m'
Error parsing date: May 25, 2022 - time data 'May 25, 2022' does not match format '%Y %d, %m'
Error parsing date: July 18, 2022 - time data 'July 18, 2022' does not match format '%Y %d, %m'
Error parsing date: April 10, 2022 - time data 'April 10, 2022' does not match format '%Y %d, %m'
Error parsing date: November 22, 2022 - time data 'November 22, 2022' does not match format '%Y %d, %m'
Error parsing date: January 22, 2025 - time data 'January 22, 2025' does not match format '%Y %d, %m'
Error parsing date: February 19, 2025 - time data 'February 19, 2025' does not match format '%Y %d, %m'
Error parsing date: February 22, 2025 - time data 'February 22, 2025' does not match format '%Y %d, %m'
Error parsing date: December 19, 2022 - time data 'December 19, 2022' does not match format '%Y %d, %m'
Error parsing date: October 24, 2022 - time data 'October 24, 2022' does not match format '%Y %d, %m'
Error parsing date: May 16, 2022 - time data 'May 16, 2022' does not match format '%Y %d, %m'
Error parsing date: April 23, 2022 - time data 'April 23, 2022' does not match format '%Y %d, %m'
Error parsing date: November 11, 2022 - time data 'November 11, 2022' does not match format '%Y %d, %m'
Error parsing date: January 11, 2025 - time data 'January 11, 2025' does not match format '%Y %d, %m'
Error parsing date: January 9, 2025 - time data 'January 9, 2025' does not match format '%Y %d, %m'
Error parsing date: August 18, 2022 - time data 'August 18, 2022' does not match format '%Y %d, %m'
Error parsing date: November 9, 2022 - time data 'November 9, 2022' does not match format '%Y %d, %m'
Error parsing date: June 6, 2022 - time data 'June 6, 2022' does not match format '%Y %d, %m'
Error parsing date: December 1, 2022 - time data 'December 1, 2022' does not match format '%Y %d, %m'
Error parsing date: February 1, 2025 - time data 'February 1, 2025' does not match format '%Y %d, %m'
Error parsing date: April 30, 2022 - time data 'April 30, 2022' does not match format '%Y %d, %m'
Error parsing date: November 2, 2022 - time data 'November 2, 2022' does not match format '%Y %d, %m'
Error parsing date: August 13, 2022 - time data 'August 13, 2022' does not match format '%Y %d, %m'
Error parsing date: January 2, 2023 - time data 'January 2, 2023' does not match format '%Y %d, %m'
Error parsing date: September 26, 2022 - time data 'September 26, 2022' does not match format '%Y %d, %m'
Error parsing date: May 5, 2025 - time data 'May 5, 2025' does not match format '%Y %d, %m'
Error parsing date: July 20, 2022 - time data 'July 20, 2022' does not match format '%Y %d, %m'
Error parsing date: December 12, 2022 - time data 'December 12, 2022' does not match format '%Y %d, %m'
Error parsing date: February 12, 2025 - time data 'February 12, 2025' does not match format '%Y %d, %m'
Error parsing date: March 27, 2022 - time data 'March 27, 2022' does not match format '%Y %d, %m'
Error parsing date: June 15, 2022 - time data 'June 15, 2022' does not match format '%Y %d, %m'
Error parsing date: April 28, 2022 - time data 'April 28, 2022' does not match format '%Y %d, %m'
Error parsing date: Unknown - time data 'Unknown' does not match format '%Y %d, %m'
Error parsing date: January 14, 2025 - time data 'January 14, 2025' does not match format '%Y %d, %m'
Error parsing date: August 5, 2022 - time data 'August 5, 2022' does not match format '%Y %d, %m'
Error parsing date: November 14, 2022 - time data 'November 14, 2022' does not match format '%Y %d, %m'
Error parsing date: April 26, 2022 - time data 'April 26, 2022' does not match format '%Y %d, %m'
Error parsing date: May 13, 2022 - time data 'May 13, 2022' does not match format '%Y %d, %m'
Error parsing date: October 21, 2022 - time data 'October 21, 2022' does not match format '%Y %d, %m'
Error parsing date: September 30, 2022 - time data 'September 30, 2022' does not match format '%Y %d, %m'
Error parsing date: February 4, 2025 - time data 'February 4, 2025' does not match format '%Y %d, %m'
Error parsing date: September 28, 2022 - time data 'September 28, 2022' does not match format '%Y %d, %m'
Error parsing date: December 4, 2022 - time data 'December 4, 2022' does not match format '%Y %d, %m'
Error parsing date: June 3, 2022 - time data 'June 3, 2022' does not match format '%Y %d, %m'
Error parsing date: March 31, 2022 - time data 'March 31, 2022' does not match format '%Y %d, %m'
Error parsing date: September 23, 2022 - time data 'September 23, 2022' does not match format '%Y %d, %m'
Error parsing date: January 7, 2025 - time data 'January 7, 2025' does not match format '%Y %d, %m'
Error parsing date: August 16, 2022 - time data 'August 16, 2022' does not match format '%Y %d, %m'
Error parsing date: November 7, 2022 - time data 'November 7, 2022' does not match format '%Y %d, %m'

In [52]:
data.head()

,title,date,text
0,"Russian Offensive Campaign Assessment, Novembe...",None,"Karolina Hird, Kateryna Stepanenko, Riley Bail..."
1,"Russian Offensive Campaign Assessment, August ...",None,"Kateryna Stepanenko, Karolina Hird, Grace Mapp..."
2,Russian Offensive Campaign Assessment: January...,None,"Russian Offensive Campaign Assessment, January..."
3,"Russian Offensive Campaign Assessment, Septemb...",None,"Karolina Hird, Kateryna Stepanenko, Grace Mapp..."
4,"Russian Offensive Campaign Assessment, October...",None,"Frederick W. Kagan October 30, 5:00 pm ET ISW ..."

In [53]:
data.date.unique()

array([None], dtype=object)

In [54]:
data.to_csv(path, index=False)